begin;
select version from private.product_revision where id=true for update;
do $$
declare actor uuid:=gen_random_uuid(); session uuid:=gen_random_uuid(); device uuid:=gen_random_uuid(); lease uuid:=gen_random_uuid(); fresh uuid:=gen_random_uuid(); doc jsonb; notice jsonb; claim jsonb; job uuid; result jsonb;
begin
 insert into auth.users(id,aud,role) values(actor,'authenticated','authenticated');
 insert into auth.sessions(id,user_id,created_at,updated_at) values(session,actor,now(),now());
 update private.product_documents set body=body||jsonb_build_array(jsonb_build_object('id',actor,'name','QA push','role','client')) where key='identities';
 perform public.product_push_device(actor,session,'register',jsonb_build_object('device',device,'token',repeat('a',64),'environment','sandbox'));
 result:=public.product_push_device(actor,session,'status',jsonb_build_object('device',device));
 if not (result->>'registered')::boolean then raise exception 'registration failed'; end if;
 notice:=jsonb_build_object('id','qa-push-'||actor,'recipient',actor,'event','booking','category','booking','booking','qa','read',false,'createdAt',floor(extract(epoch from now())*1000)::bigint);
 update private.product_documents set body=body||jsonb_build_array(notice) where key='notices';
 if (select count(*) from private.push_outbox where recipient=actor)<>1 then raise exception 'atomic queue missing'; end if;
 update private.product_documents set body=body where key='notices';
 if (select count(*) from private.push_outbox where recipient=actor)<>1 then raise exception 'duplicate queue'; end if;
 claim:=public.product_push_claim(lease,20);
 select id into job from private.push_outbox where recipient=actor;
 if not public.product_push_eligible(job,lease) then raise exception 'claim ineligible'; end if;
 update private.product_documents set body=(select jsonb_agg(case when x->>'id'=notice->>'id' then x||'{"read":true}'::jsonb else x end) from jsonb_array_elements(body) x) where key='notices';
 if public.product_push_eligible(job,lease) then raise exception 'read notification still eligible'; end if;
 update private.product_documents set body=(select jsonb_agg(case when x->>'id'=notice->>'id' then x||'{"read":false}'::jsonb else x end) from jsonb_array_elements(body) x) where key='notices';

 perform public.product_push_claim(fresh,20);
 if not public.product_push_eligible(job,lease) then raise exception 'lease stolen'; end if;
 perform public.product_push_finish(job,fresh,'accepted');
 if (select status from private.push_outbox where id=job)<>'sending' then raise exception 'wrong worker accepted'; end if;
 perform public.product_push_device(actor,session,'preferences',jsonb_build_object('device',device,'categories',jsonb_build_object('booking',false)));
 if public.product_push_eligible(job,lease) then raise exception 'preference ignored'; end if;
 perform public.product_push_device(actor,session,'preferences',jsonb_build_object('device',device,'categories',jsonb_build_object('booking',true)));
 perform public.product_push_finish(job,lease,'pending','temporary');
 if (select attempts from private.push_outbox where id=job)<>1 or (select due_at from private.push_outbox where id=job)<=now() then raise exception 'retry not delayed'; end if;
 update private.push_outbox set due_at=now() where id=job;
 perform public.product_push_claim(fresh,20);
 perform public.product_push_finish(job,fresh,'failed','Unregistered',true);
 if (select enabled from private.push_devices where id=device) then raise exception 'bad token not disabled'; end if;
 perform public.product_push_device(actor,session,'register',jsonb_build_object('device',device,'token',repeat('b',64),'environment','sandbox'));
 notice:=notice||jsonb_build_object('id','qa-new-booking-'||actor,'event','booking');
 update private.product_documents set body=body||jsonb_build_array(notice) where key='notices';
 notice:=notice||jsonb_build_object('id','qa-cancel-'||actor,'event','cancelled');
 update private.product_documents set body=body||jsonb_build_array(notice) where key='notices';
 if exists(select 1 from private.push_outbox where recipient=actor and category='booking' and status in ('pending','sending')) then raise exception 'obsolete confirmation still queued'; end if;
 notice:=notice||jsonb_build_object('id','qa-second-'||actor,'event','message');
 update private.product_documents set body=body||jsonb_build_array(notice) where key='notices';
 delete from auth.sessions where id=session;
 if exists(select 1 from private.push_devices where id=device) then raise exception 'session did not cascade'; end if;
 if exists(select 1 from private.push_outbox where recipient=actor) then raise exception 'queue did not cascade'; end if;
 if has_function_privilege('anon','public.product_push_claim(uuid,integer)','execute') or has_function_privilege('authenticated','public.product_push_device(uuid,uuid,text,jsonb)','execute') then raise exception 'public RPC access'; end if;
 if has_table_privilege('authenticated','private.push_devices','select') then raise exception 'tokens exposed'; end if;
 raise notice 'PASS: registration, atomic outbox, duplicate exclusion, leases, preferences, retries, invalid tokens, revoked sessions, private grants';
end $$;
rollback;
