from pathlib import Path
import json
p=Path('work/partant.template.html');s=p.read_text();extra=Path('work/onboarding-sectors.js').read_text().replace('__COMMUNES__',json.dumps(json.load(open('work/communes-idf.json')),ensure_ascii=False,separators=(',',':')))
s=s.replace('const customerDefaults=',extra+'\nconst customerDefaults=')
s=s.replace("function onboarding(){let i=state.onboardStep;", "function onboarding(){setPractice(customer.sport);let i=state.onboardStep;")
s=s.replace("['Tout','Préparation physique','Running','Pilates','Musculation','Boxe','Yoga','Mobilité','Remise en forme','Tennis','Natation'],customer.sport", "Object.keys(sportGoals),customer.sport")
s=s.replace("['Me remettre en forme','Gagner en force','Me sentir mieux','Préparer une course','Améliorer ma mobilité','Découvrir une pratique','Perdre du poids'],customer.goal)}", "goalsFor(customer.sport),customer.goal)}<p id=\"goal-context\" role=\"status\" class=\"small muted subhead\">Des objectifs adaptés à votre pratique.</p>")
s=s.replace("${selectField('Votre secteur','city',['Paris 11e','Paris','Lyon','Bordeaux','Marseille'],customer.city)}", "<div class=\"field\"><span>Votre secteur</span><button type=\"button\" class=\"pill light full row between\" data-action=\"location\" style=\"text-align:left;height:auto;min-height:50px;white-space:normal\"><span>${esc(customer.city)}</span>${ic('pin','sm')}</button><small class=\"muted\">Commune, arrondissement ou code postal · Île-de-France</small></div>")
s=s.replace("Paris est la ville pilote de la démo. Pour les autres villes, la visio reste accessible.","Tous les secteurs franciliens sont sélectionnables. Les coachs fictifs sont à Paris ; ailleurs, essayez la visio.")
s=s.replace("case 'discard-config':", "case 'location':openSectors();return;\ncase 'choose-sector':chooseSector(d.id);return;\ncase 'more-sectors':state.sectorLimit+=30;document.getElementById('sector-results').innerHTML=sectorRows();return;\ncase 'discard-config':")
s=s.replace("if(id==='onboard-form'){for(let [k,v]of f.entries())customer[k]=['budget','distance'].includes(k)?+v:v;persist();", "if(id==='onboard-form'){for(let [k,v]of f.entries())customer[k]=['budget','distance'].includes(k)?+v:v;setPractice(customer.sport);persist();")
# Keep local offer state explicit when a commune has no seeded coaches.
s=s.replace("<h2>Aucun coach sur ce créneau</h2><p>Essayez une autre heure, un budget plus large ou une séance en visio.</p>","<h2>${!state.city.startsWith('Paris')&&state.format!=='Visio'?'Pas encore de coach dans ce secteur':'Aucun coach sur ce créneau'}</h2><p>${!state.city.startsWith('Paris')&&state.format!=='Visio'?'Les profils fictifs de la démo sont à Paris. Votre secteur est enregistré ; vous pouvez rechercher une séance en visio.':'Essayez une autre heure, un budget plus large ou une séance en visio.'}</p>${!state.city.startsWith('Paris')&&state.format!=='Visio'?'<button class=\"pill\" data-action=\"search-visio\">Voir les coachs en visio</button>':''}")
s=s.replace("case 'location':openSectors();return;", "case 'search-visio':state.format='Visio';render();return;\ncase 'location':openSectors();return;")
s=s.replace("state.auth=null;Object.assign(customer,customerDefaults);", "state.auth=null;delete customer.cityCode;Object.assign(customer,customerDefaults);")
p.write_text(s)
