// Finalisation du prototype : accès, calendrier, exploitation et incidents.
// Les services externes restent simulés. Ce module est intégré au HTML par le build.
identity.payments??=[];identity.proposals??=[];identity.reminderKeys??=[];identity.refundLedger??=[];
const finalBase={render,act,go,bindAccount,doPay,allSlots,configPage,configSave,scheduleFits,canScheduleGroup,coachSession,operationsPage,notificationTitle,notificationDescription,notificationEnabled,alertCandidates,alertsPage,checkout,resetIdentityDemo};
function saveRuntime(){localStorage.setItem('partant-runtime',JSON.stringify(runtime))}
function signedClient(){return state.auth?.role==='client'&&!state.auth.deleted}
function requireClient(){if(signedClient())return true;state.pendingCheckout=state.booking?clone(state.booking):null;state.entryRole='client';state.entryMode='login';state.history=[];finalBase.go('login');toast('Connectez-vous pour retrouver et confirmer votre séance.');return false}
go=function(screen){if(runtime.mode!=='demo'&&['accounts','operations'].includes(screen)){toast('Ouvrez le mode Test dans À propos de la simulation.');return}if(screen==='checkout'&&!requireClient())return;finalBase.go(screen)};
bindAccount=function(account){finalBase.bindAccount(account);state.coachDay=todayIndex();state.profileDay=todayIndex();state.day=Math.max(todayIndex(),state.day);state.paymentAttempt=null};
doPay=function(){if(!requireClient()||!state.booking)return;let oldScreen=state.screen;state.screen='checkout';try{finalBase.doPay()}finally{if(state.screen==='checkout')state.screen=oldScreen}};
function futureDays(){extendDays();return days.map((d,i)=>[i,d.long]).filter(([i])=>i>=todayIndex()&&i<todayIndex()+90)}
dateStrip=function(selected,action){let start=state.dateWindows?.[action]??Math.max(todayIndex(),selected);start=Math.min(Math.max(todayIndex(),start),todayIndex()+83);return `<div class="row between space"><button class="iconbtn soft" data-action="calendar-week" data-target="${action}" data-id="${start-7}" aria-label="Semaine précédente" ${start<=todayIndex()?'disabled':''}>${ic('back','sm')}</button><strong class="small">${days[start].d.toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</strong><button class="iconbtn soft" data-action="calendar-week" data-target="${action}" data-id="${start+7}" aria-label="Semaine suivante" ${start>=todayIndex()+83?'disabled':''}>${ic('arrow','sm')}</button></div><div class="scrollrow" aria-label="Choisir un jour">${days.slice(start,start+7).map((d,j)=>`<button class="datebtn ${start+j===selected?'active':''}" data-action="${action}" data-id="${start+j}" aria-label="${d.long}" aria-pressed="${start+j===selected}"><span>${d.short}</span><b>${d.num}</b></button>`).join('')}</div>`};
function intervalsFor(p,day){if(p.exceptions&&Object.hasOwn(p.exceptions,day))return p.exceptions[day];if(p.intervals)return p.intervals[((day%7)+7)%7]||[];if(!p.week[((day%7)+7)%7])return [];return p.useBreak?[[p.start,p.breakStart],[p.breakEnd,p.end]]:[[p.start,p.end]]}
function intervalFits(p,day,time,duration){return intervalsFor(p,day).some(([a,b])=>mins(time)>=mins(a)&&mins(time)+duration<=mins(b))}
allSlots=function(c,d){if(d<todayIndex()||!days[d])return [];let p=ownerConfig(c.id);if(!p.intervals&&!Object.hasOwn(p.exceptions||{},d))return finalBase.allSlots(c,d);if(p.daysOff.includes(d)&&!Object.hasOwn(p.exceptions||{},d))return [];let duration=selectedService(c.id).duration,out=[];for(let [a,b] of intervalsFor(p,d))for(let t=mins(a);t+duration<=mins(b);t+=30)out.push(clockText(t));return [...new Set(out)].sort()};
scheduleFits=function(duration,...args){if(cfg.intervals&&!args.length)return cfg.intervals.some(list=>list.some(([a,b])=>mins(b)-mins(a)>=duration));return finalBase.scheduleFits(duration,...args)};
canScheduleGroup=function(s,d,time){if(!Number.isInteger(d)||d<todayIndex()||d>=todayIndex()+cfg.horizon||!days[d]||!/^\d\d:\d\d$/.test(time)||hoursUntil({day:d,time})<cfg.notice)return 'Choisissez une date ouverte dans votre horizon de réservation.';if(!intervalFits(cfg,d,time,s.duration)||cfg.daysOff.includes(d))return 'Ce cours doit tenir dans une plage ouverte de cette journée.';let t=mins(time);if(state.closed.includes(key(activeCoachId,d,time))||state.bookings.some(b=>b.coach===activeCoachId&&b.day===d&&b.status!=='cancelled'&&overlaps(t,s.duration,mins(b.time),b.duration||60,cfg.buffer))||operations.groups.some(g=>g.coach===activeCoachId&&g.day===d&&g.status==='open'&&overlaps(t,s.duration,mins(g.time),g.duration,cfg.buffer))||cfg.privateEvents.some(e=>e.day===d&&overlaps(t,s.duration,mins(e.start),mins(e.end)-mins(e.start),cfg.buffer)))return 'Cette plage chevauche une séance, un cours ou une indisponibilité.';if(!cfg.formats.includes(s.groupFormat)||s.groupFormat==='Domicile')return 'Activez un lieu compatible avec cette offre.';return ''};
const weekdayNames=['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche'];
function editableIntervals(p){return Array.from({length:7},(_,d)=>clone(intervalsFor({...p,exceptions:{}},d)))}
function intervalInputs(day,list){return `<details class="day-interval" ${day===0?'open':''}><summary><strong>${weekdayNames[day]}</strong><span class="small muted">${list.length?list.map(x=>x.join('–')).join(' · '):'Fermé'}</span></summary><fieldset style="border:0;padding:0;margin:12px 0 0"><legend class="sr-only">Plages du ${weekdayNames[day]}</legend><label class="check-row"><input type="checkbox" name="open-${day}" ${list.length?'checked':''}>Journée ouverte</label>${[0,1,2].map(i=>`<div class="split">${inputField('Début '+(i+1),'start-'+day+'-'+i,list[i]?.[0]||'','time')}${inputField('Fin '+(i+1),'end-'+day+'-'+i,list[i]?.[1]||'','time')}</div>`).join('')}</fieldset></details>`}
function schedulePage(){let p=cfg;return `${pagebar('Horaires & exceptions')}<div class="section"><h1>À votre rythme.</h1><p class="muted space">Jusqu’à trois plages par jour. Laissez les plages inutilisées vides.</p><form id="weekly-form">${editableIntervals(p).map((list,d)=>intervalInputs(d,list)).join('')}<p class="note space">Les séances déjà confirmées sont conservées lorsque vous changez vos horaires.</p><p id="weekly-error" role="alert"></p><button class="pill full space">Enregistrer la semaine</button></form><h2 class="space">Exceptions datées</h2><p class="small muted space">Une journée particulière remplace la semaine type.</p>${Object.entries(p.exceptions||{}).sort(([a],[b])=>a-b).map(([d,list])=>`<div class="setting-row"><span>${dayLabel(+d)}<small>${list.length?list.map(x=>x.join('–')).join(' · '):'Fermé'}</small></span><button class="textbtn" data-action="remove-exception" data-id="${d}">Retirer</button></div>`).join('')}<button class="pill light full space" data-action="add-exception">Ajouter une exception</button></div>`}
function parseIntervals(f,day){let list=[];if(!f.has('open-'+day))return list;for(let i=0;i<3;i++){let a=f.get('start-'+day+'-'+i),b=f.get('end-'+day+'-'+i);if(!a&&!b)continue;if(!/^\d\d:\d\d$/.test(a||'')||!/^\d\d:\d\d$/.test(b||'')||mins(a)>=mins(b)||mins(b)>1440)throw Error('Chaque plage doit avoir un début et une fin valides.');list.push([a,b])}list.sort((a,b)=>mins(a[0])-mins(b[0]));if(!list.length)throw Error('Ajoutez une plage ou fermez cette journée.');if(list.some((x,i)=>i&&mins(x[0])<mins(list[i-1][1])))throw Error('Deux plages ne peuvent pas se chevaucher.');return list}
function paymentProblem(b){if(!b)return 'La sélection a été perdue. Choisissez une nouvelle séance.';return coachContext(b.coach,()=>{if(b.groupSessionId){let g=groupById(b.groupSessionId);if(!g||!groupPublic(g)||groupSeats(g)<b.participants)return 'Les places demandées ne sont plus disponibles.';if(g.unitPrice!==b.unitPrice||g.unitPrice*b.participants!==b.quotedTotal)return 'Le tarif a changé. Vérifiez votre sélection.'}else{let s=servicesFor(b.coach).find(s=>s.id===b.serviceId);if(!s||s.duration!==b.duration||s.price!==b.offerPrice||!cfg.formats.includes(b.format)||b.quotedTotal!==bookingPrice(b)||b.quotedLocation&&b.quotedLocation!==JSON.stringify(locationFor(b))||b.cancelHours!==cfg.cancelHours)return 'L’offre a changé. Vérifiez les nouveaux détails.';let old=state.screen;state.screen='checkout';let available=avail(coaches[b.coach],b.day).includes(b.time);state.screen=old;if(!available)return 'Ce créneau n’est plus disponible.'}if(state.bookings.some(x=>x.customerId===currentCustomerId&&x.status==='confirmed'&&x.day===b.day&&overlaps(mins(x.time),x.duration||60,mins(b.time),b.duration)))return 'Une autre séance est déjà prévue à cette heure.';return ''})}
function beginPayment(){if(!requireClient())return;let done=identity.payments.find(p=>p.id===state.paymentAttempt&&p.owner===actorId()&&p.status==='paid');if(done){state.selectedBooking=done.bookingId;go('confirmation');return}let b=state.booking,issue=paymentProblem(b);if(issue){state.paymentIssue=issue;go('payment-lost');return}let existing=identity.payments.find(p=>p.id===state.paymentAttempt);if(existing?.status==='paid'){state.selectedBooking=existing.bookingId;go('confirmation');return}if(!existing||existing.owner!==actorId()||existing.fingerprint!==JSON.stringify(b)){existing={id:'pay-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),owner:actorId(),fingerprint:JSON.stringify(b),selection:clone(b),status:'pending',createdAt:appNow().getTime()};identity.payments.push(existing);state.paymentAttempt=existing.id}existing.status='pending';persist();go('payment')}
function settlePayment(outcome){let p=identity.payments.find(x=>x.id===state.paymentAttempt);if(!p||p.owner!==actorId())return;if(p.status==='paid'){state.selectedBooking=p.bookingId;go('confirmation');return}if(outcome!=='success'){p.status=outcome==='refused'?'refused':'interrupted';persist();render();return}if(appNow().getTime()-p.createdAt>10*60000){p.status='expired';persist();render();return}state.booking=clone(p.selection);let problem=paymentProblem(state.booking);if(problem){p.status='lost';state.paymentIssue=problem;persist();go('payment-lost');return}let n=state.bookings.length;doPay();if(state.bookings.length===n+1){p.status='paid';p.bookingId=state.selectedBooking;state.bookings.at(-1).paymentId=p.id;persist()}else{p.status='lost';persist();go('payment-lost')}}
function paymentPage(){let p=identity.payments.find(x=>x.id===state.paymentAttempt),b=state.booking,status=p?.status||'pending';let headings={pending:'Un dernier geste.',refused:'Paiement refusé.',interrupted:'Paiement interrompu.',expired:'Votre tentative a expiré.'};return `${pagebar('Paiement sécurisé · simulation')}<div class="section"><p class="eyebrow muted">${status==='pending'?'EN ATTENTE DE CONFIRMATION':'AUCUN DÉBIT EFFECTUÉ'}</p><h1 class="space">${headings[status]||'Vérifier le paiement'}</h1>${b?summaryPerson(b):''}<div class="ticket"><strong>${b?dayLabel(b.day)+' · '+b.time:''}</strong><p class="space">${b?.kind==='Duo'?2:b?.participants||1} participant(s) · ${b?.quotedTotal||0} € au total</p></div><p class="note">${status==='pending'?'Votre séance est confirmée uniquement après validation. Le créneau reste disponible pour les autres utilisateurs.':'Aucune réservation n’a été créée. Votre sélection est conservée pour une nouvelle tentative.'}</p>${status==='pending'?'<button class="pill full space" data-action="payment-result" data-id="success">Valider le paiement simulé</button><button class="textbtn full space" data-action="payment-result" data-id="interrupted">Interrompre et revenir plus tard</button>':'<button class="pill full space" data-action="retry-payment">Réessayer avec ma sélection</button>'}${runtime.mode==='demo'&&status==='pending'?'<button class="pill light full space" data-action="payment-result" data-id="refused">Tester un refus bancaire</button>':''}<button class="textbtn full space" data-action="payment-summary">Revoir le récapitulatif</button><p class="small muted space">Aucun service bancaire connecté. Ne saisissez aucune donnée bancaire réelle.</p></div>`}
function paymentLost(){return `${pagebar('Sélection à actualiser')}<div class="section"><h1>On trouve<br>un autre moment ?</h1><p class="note space">${esc(state.paymentIssue||'La sélection n’est plus disponible.')} Aucun débit ni réservation.</p><button class="pill full space" data-action="payment-reselect">Revoir les disponibilités</button></div>`}
checkout=function(){let html=finalBase.checkout();return html.replace('Réserver ·','Continuer vers le paiement ·')};
function refundPanel(b){let rows=identity.refundLedger.filter(x=>x.bookingId===b.id);return rows.length?`<section class="note space"><h3>Suivi des remboursements</h3>${rows.map(r=>`<p class="space">${r.amount} € · ${r.status==='pending'?'En cours de traitement':'Remboursement confirmé'}${runtime.mode==='demo'&&r.status==='pending'?`<button class="textbtn full" data-action="settle-refund" data-id="${r.id}">Simuler la confirmation bancaire</button>`:''}</p>`).join('')}<p class="small muted space">Mouvements fictifs, sans remboursement bancaire réel.</p></section>`:''}
function accountSettings(){if(!state.auth)return `${pagebar('Mon compte')}<div class="section"><h1>On se retrouve ?</h1><button class="pill full space" data-action="entry-next">Me connecter</button></div>`;let a=identity.accounts.find(x=>x.id===actorId()),name=a.role==='coach'?cfg.name:customer.name;return `${pagebar('Mon compte')}<div class="section"><h1>Vos informations.</h1><form id="account-form">${inputField('Prénom / nom public','name',name,'text','required maxlength="60"')}${inputField('Adresse e-mail fictive','email',a.email,'email','required maxlength="160"')}${inputField('Téléphone facultatif','phone',a.phone||'','tel','maxlength="25"')}<label class="check-row"><input type="checkbox" name="reminders" ${(a.role==='coach'?cfg.notifications.reminder:customer.reminders)?'checked':''}>Rappels avant mes séances</label>${a.role==='client'?`<label class="check-row"><input type="checkbox" name="alerts" ${customer.alertNotifications!==false?'checked':''}>Alertes de disponibilité</label>`:''}<p id="account-error" role="alert"></p><button class="pill full space">Enregistrer</button></form><button class="setting-row" data-action="export-account"><span>Exporter mes données locales</span>${ic('arrow','sm')}</button><button class="setting-row" data-action="logout"><span>Me déconnecter</span>${ic('chevron')}</button><button class="setting-row" data-action="delete-account"><span>Supprimer mon compte de démonstration</span>${ic('chevron')}</button><p class="small muted space">Connexion par code de démonstration. En production, tout changement d’e-mail nécessitera une nouvelle vérification.</p></div>`}
function ownExport(){let a=identity.accounts.find(x=>x.id===actorId()),bs=state.bookings.filter(canReadBooking),ids=new Set(bs.map(b=>b.id));return {exportedAt:appNow().toISOString(),account:a,profile:a.role==='coach'?clone(cfg):clone(customer),bookings:bs,messages:Object.fromEntries(Object.entries(identity.messages).filter(([id])=>ids.has(id))),notifications:myNotifications(),payments:identity.payments.filter(p=>p.owner===a.id)}}
function deleteOwnAccount(){let a=identity.accounts.find(x=>x.id===actorId());if(!a)return;if(state.bookings.some(b=>canReadBooking(b)&&b.status==='confirmed'))return toast('Traitez vos séances confirmées avant de supprimer ce compte.');let id=a.id;if(a.role==='coach'){cfg.published=false;cfg.name='Compte supprimé';cfg.bio='';cfg.photoData='';cfg.business={};cfg.documentCase=null}else identity.customers[a.customerId]={...customerDefaults,name:'Compte supprimé',favorites:[]};identity.messages=Object.fromEntries(Object.entries(identity.messages).map(([k,ms])=>[k,ms.map(m=>m.sender===id?{...m,text:'Message supprimé',sender:'deleted'}:m)]));identity.events=identity.events.filter(n=>n.recipient!==id);identity.payments=identity.payments.filter(p=>p.owner!==id);for(let b of state.bookings)if(a.role==='client'&&b.customerId===a.customerId){b.clientName='Compte supprimé';b.home='';b.goal='';if(b.format==='Domicile')b.location={name:'Adresse supprimée',address:''}}identity.accounts=identity.accounts.filter(x=>x.id!==id);state.pendingCheckout=null;bindAccount(null);persist();closeModal();render();toast('Compte local supprimé. Les références des séances sont conservées chez les interlocuteurs.')}
const docLabels={draft:'À compléter',pending:'En cours d’examen',correction:'Correction demandée',rejected:'Dossier refusé',approved:'Vérifié · simulation',expired:'Justificatifs expirés'};
function dossier(p=cfg){return p.documentCase||{status:p.verified?'approved':'draft',legacy:true,history:[]}}
function documentsPage(){let d=dossier();return `${pagebar('Justificatifs coach')}<div class="section"><h1>La confiance<br>se construit.</h1><span class="badge space">${docLabels[d.status]}</span>${d.reason?'<div class="note space">'+esc(d.reason)+'</div>':''}${d.expires?'<p class="small muted space">Validité jusqu’au '+esc(d.expires)+'</p>':''}${d.status==='pending'?'<p class="note space">Votre dossier fictif attend une décision de l’équipe. Les nouvelles réservations restent fermées.</p>':`<form id="documents-form" class="space"><p class="small muted">Déposez des références fictives, aucun document personnel réel.</p>${['Identité','Qualification / diplôme','Carte professionnelle ou justification','Assurance professionnelle'].map((label,i)=>inputField(label,'doc-'+i,d.documents?.[i]||'','text','required maxlength="100" placeholder="Ex. document-test.pdf"')).join('')}${inputField('Date de fin de validité','expires',d.expires||isoForDay(todayIndex()+365),'date','required min="'+isoForDay(todayIndex()+1)+'"')}<button class="pill full space">Soumettre le dossier fictif</button></form>`}<h2 class="space">Historique</h2>${(d.history||[]).map(h=>`<p class="small space">${esc(h.date)} · ${docLabels[h.status]}<br>${esc(h.reason||'')}</p>`).join('')||'<p class="muted space">Profil de démonstration initial.</p>'}<p class="small muted space">Le badge repose ici sur une décision de simulation. Aucun document n’est réellement contrôlé.</p></div>`}
function reviewDossier(id){if(runtime.mode!=='demo')return;let p=ownerConfig(id),d=dossier(p);if(d.status!=='pending')return;state.reviewCoach=id;showModal('Examiner le dossier · '+p.name,`<p class="small muted">Équipe Partant · simulation</p><div class="note space">${d.documents.map(esc).join('<br>')}<br>Validité : ${esc(d.expires)}</div><form id="document-review-form" class="space">${selectField('Décision','status',[['approved','Valider'],['correction','Demander une correction'],['rejected','Refuser']],'approved')}<label class="field">Motif<textarea name="reason" required maxlength="500"></textarea></label><button class="pill full">Enregistrer la décision</button></form>`)}
function customEvent(recipient,title,text,extra={}){identity.events.push({id:'event-'+(++identity.eventSequence),recipient,kind:'custom',category:'changes',title,text,at:appNow().getTime(),read:false,...extra})}
operationsPage=function(){return finalBase.operationsPage()+`<div class="section"><h2>Dossiers coachs</h2>${coaches.map(c=>{let d=dossier(ownerConfig(c.id));return `<div class="booking-row"><strong>${esc(c.name)}</strong><p class="space">${docLabels[d.status]}</p>${d.status==='pending'?`<button class="pill light full space" data-action="review-dossier" data-id="${c.id}">Examiner</button>`:''}</div>`}).join('')}</div>`};
function proposalFor(id){return identity.proposals.find(x=>x.id===id)}
function pendingProposals(b){return identity.proposals.filter(p=>p.bookingId===b.id&&p.status==='pending')}
function proposalForm(id){let b=bookingRecord(id);if(state.auth?.role!=='coach'||b?.coach!==activeCoachId||b.status!=='confirmed'||hoursUntil(b)<=0)return;state.proposalBooking=id;let current=locationFor(b);showModal('Proposer un changement',`<p>La réservation initiale reste confirmée jusqu’à l’accord du client. Aucun supplément n’est facturé.</p><form id="proposal-form" class="space">${b.groupSessionId?selectField('Cours de remplacement','group',operations.groups.filter(g=>g.coach===b.coach&&g.id!==b.groupSessionId&&groupPublic(g)&&groupSeats(g)>=b.participants&&g.unitPrice===b.unitPrice).map(g=>[g.id,g.name+' · '+dayLabel(g.day)+' '+g.time]),''):`${selectField('Nouvelle date','day',futureDays(),b.day)}${inputField('Horaire','time',b.time,'time','required')}${inputField('Lieu','place',current.name,'text','required maxlength="100"')}${inputField('Adresse','address',current.address,'text','required maxlength="180"')}`}<label class="field">Message au client<textarea name="reason" required maxlength="500" placeholder="Expliquez le changement proposé."></textarea></label><p id="proposal-error" role="alert"></p><button class="pill full space">Envoyer la proposition</button><p class="small muted space">${b.groupSessionId?'Le transfert concerne toutes les places de cette réservation, vers un cours du même coach au même tarif.':'Le prix et la durée réservés sont conservés.'}</p></form>`)}
function proposalIssue(b,to){if(b.status!=='confirmed'||hoursUntil(b)<=0)return 'La réservation initiale n’est plus modifiable.';if(to.groupSessionId){let g=groupById(to.groupSessionId);if(!g||g.coach!==b.coach||g.id===b.groupSessionId||!groupPublic(g)||g.unitPrice!==b.unitPrice||g.day!==to.day||g.time!==to.time||JSON.stringify(g.location)!==JSON.stringify(to.location)||groupSeats(g)<b.participants)return 'Les places ou les conditions du cours ont changé.'}else{let p=ownerConfig(b.coach);if(hoursUntil(to)<2||to.day>=todayIndex()+p.horizon||!intervalFits(p,to.day,to.time,b.duration)||p.daysOff.includes(to.day)||state.closed.includes(key(b.coach,to.day,to.time)))return 'Le moment proposé n’est plus ouvert.';if(state.bookings.some(x=>x.id!==b.id&&x.coach===b.coach&&x.day===to.day&&x.status!=='cancelled'&&overlaps(mins(x.time),x.duration||60,mins(to.time),b.duration,p.buffer))||operations.groups.some(g=>g.coach===b.coach&&g.status==='open'&&g.day===to.day&&overlaps(mins(g.time),g.duration,mins(to.time),b.duration,p.buffer))||p.privateEvents.some(e=>e.day===to.day&&overlaps(mins(e.start),mins(e.end)-mins(e.start),mins(to.time),b.duration,p.buffer)))return 'Le coach n’est plus disponible à ce moment.'}if(state.bookings.some(x=>x.id!==b.id&&x.customerId===b.customerId&&x.status==='confirmed'&&x.day===to.day&&overlaps(mins(x.time),x.duration||60,mins(to.time),to.duration||b.duration)))return 'Le client a déjà une autre séance à ce moment.';return ''}
function proposalPage(){let p=proposalFor(state.proposalId),b=p&&bookingRecord(p.bookingId);if(!p||!b||!canReadBooking(b))return pagebar('Proposition indisponible');return `${pagebar('Changement proposé')}<div class="section"><h1>Un autre moment ?</h1><p class="space">${esc(p.reason)}</p><div class="ticket"><p class="eyebrow muted">RÉSERVATION ACTUELLE</p><h3 class="space">${dayLabel(b.day)} · ${b.time}</h3><p>${esc(locationFor(b).name)}</p><div class="sep"></div><p class="eyebrow muted">PROPOSITION</p><h3 class="space">${dayLabel(p.to.day)} · ${p.to.time}</h3><p>${esc(p.to.location.name)}<br>${esc(p.to.location.address)}</p><p class="small space">${p.to.duration||b.duration} min · ${esc(p.to.format||b.format)} · conditions d’annulation conservées</p><p class="small space">Prix conservé : ${netPaid(b)} € · ${b.kind==='Duo'?2:b.participants||1} participant(s)</p></div><span class="badge">${{pending:'En attente de réponse',accepted:'Acceptée',declined:'Refusée',expired:'Expirée',withdrawn:'Retirée'}[p.status]}</span>${p.status==='pending'&&signedClient()?`<p class="note space">Vous êtes libre de refuser. Votre séance initiale restera confirmée. À l’acceptation, les disponibilités sont revérifiées.</p><button class="pill full space" data-action="proposal-answer" data-id="accepted">Accepter le changement</button><button class="pill light full space" data-action="proposal-answer" data-id="declined">Garder ma séance initiale</button>`:''}${p.status==='pending'&&state.auth?.role==='coach'?'<button class="pill light full space" data-action="proposal-withdraw">Retirer ma proposition</button>':''}<button class="textbtn full space" data-action="message" data-id="${b.id}">En parler dans la conversation</button></div>`}
function answerProposal(status){let p=proposalFor(state.proposalId),b=p&&bookingRecord(p.bookingId);if(!p||p.status!=='pending'||!signedClient()||b?.customerId!==currentCustomerId)return;if(status==='accepted'){if(JSON.stringify(bookingEventSnapshot(b))!==p.fingerprint||JSON.stringify(locationFor(b))!==p.locationFingerprint){p.status='expired';persist();render();return toast('La séance a changé. Demandez une nouvelle proposition.')}let issue=proposalIssue(b,p.to);if(issue){toast(issue+' Votre séance initiale est conservée.');return}Object.assign(b,p.to);operations.checks[b.id]={};}p.status=status;p.answeredAt=appNow().getTime();customEvent('coach-'+b.coach,status==='accepted'?'Proposition acceptée':'Proposition refusée',status==='accepted'?'Le client a accepté le nouveau rendez-vous.':'La séance initiale reste confirmée.',{bookingId:b.id,proposalId:p.id});persist();render()}
function proposalPanel(b){let ps=identity.proposals.filter(p=>p.bookingId===b.id);return ps.length?`<section class="note space"><h3>Propositions du coach</h3>${ps.map(p=>`<button class="setting-row" data-action="open-proposal" data-id="${p.id}"><span>${dayLabel(p.to.day)} · ${p.to.time}<small>${{pending:'Réponse attendue',accepted:'Acceptée',declined:'Refusée',expired:'Expirée',withdrawn:'Retirée'}[p.status]}</small></span>${ic('chevron')}</button>`).join('')}</section>`:''}
notificationTitle=function(n){return n.kind==='custom'?esc(n.title):finalBase.notificationTitle(n)};
notificationDescription=function(n){return n.kind==='custom'?esc(n.text):finalBase.notificationDescription(n)};
notificationEnabled=function(n){if(n.category==='reminder')return state.auth?.role==='coach'?cfg.notifications.reminder!==false:customer.reminders!==false;if(n.category==='availability')return customer.alertNotifications!==false;return finalBase.notificationEnabled(n)};
alertCandidates=function(a){let old={screen:state.screen,repeatOffer:state.repeatOffer,profileService:state.profileService,serviceFilter:state.serviceFilter};Object.assign(state,{screen:'explore',repeatOffer:null,profileService:null,serviceFilter:'Tous'});try{return finalBase.alertCandidates(a).filter(m=>(a.groupOnly?m.groupId&&groupSeats(groupById(m.groupId))>=(a.participants||1):!m.groupId||groupSeats(groupById(m.groupId))>=(a.participants||1))&&!state.bookings.some(b=>b.customerId===a.customerId&&b.status==='confirmed'&&b.day===m.day&&overlaps(mins(b.time),b.duration||60,mins(m.time),m.duration||primaryService(m.coach).duration)))}finally{Object.assign(state,old)}};
alertsPage=function(){let html=finalBase.alertsPage();return html.replaceAll('data-action="delete-alert"', 'data-action="delete-alert"')+`<div class="section">${operations.alerts.filter(a=>a.customerId===currentCustomerId&&a.status!=='booked').map(a=>`<button class="setting-row" data-action="alert-places" data-id="${a.id}"><span>${esc(alertDescription(a))}<small>${a.groupOnly?'Groupe uniquement · ':''}${a.participants||1} place(s) souhaitée(s) · ajuster</small></span>${ic('chevron')}</button>`).join('')}</div>`};
function temporalMaintenance(){extendDays();let changed=false;for(let b of state.bookings){if(b.status==='confirmed'&&hoursUntil(b)+(b.duration||60)/60<=0){b.status='completed';b.completedAutomatically=true;changed=true}let recorded=identity.refundLedger.filter(r=>r.bookingId===b.id).reduce((n,r)=>n+r.amount,0);if((b.refund||0)>recorded){identity.refundLedger.push({id:'refund-'+b.id+'-'+b.refund,bookingId:b.id,amount:b.refund-recorded,status:'pending',createdAt:appNow().getTime()});changed=true}if(b.status==='confirmed'&&hoursUntil(b)>0&&hoursUntil(b)<=24){for(let recipient of ['coach-'+b.coach,identity.accounts.find(a=>a.customerId===b.customerId)?.id].filter(Boolean)){let k=recipient+'|'+b.id+'|'+b.day+'|'+b.time;if(!identity.reminderKeys.includes(k)){identity.reminderKeys.push(k);let a=identity.accounts.find(x=>x.id===recipient),enabled=a?.role==='coach'?ownerConfig(a.coachId).notifications.reminder!==false:identity.customers[b.customerId]?.reminders!==false;if(enabled)customEvent(recipient,'Votre séance approche',dayLabel(b.day)+' à '+b.time+' · '+coaches[b.coach].name,{bookingId:b.id,category:'reminder'});changed=true}}}}
for(let p of Object.values(identity.configs)){let d=p.documentCase;if(d?.status==='approved'&&d.expires<parisISO()){d.status='expired';p.verified=false;p.published=false;changed=true}}
for(let p of identity.proposals){let b=bookingRecord(p.bookingId);if(p.status==='pending'&&(!b||b.status!=='confirmed'||hoursUntil(b)<=0||hoursUntil(p.to)<=0)){p.status='expired';changed=true}}
for(let a of operations.alerts.filter(a=>a.status==='active'&&a.day>=todayIndex())){let oldFilter=state.serviceFilter;state.serviceFilter='Tous';let matches=alertCandidates(a);state.serviceFilter=oldFilter;let keys=matches.map(m=>m.coach+'|'+m.day+'|'+m.time+'|'+(m.groupId||'solo')),fresh=keys.some(k=>!(a.seenMatches||[]).includes(k));if(JSON.stringify(keys)!==JSON.stringify(a.seenMatches)){a.seenMatches=keys;changed=true}if(fresh&&identity.customers[a.customerId]?.alertNotifications!==false){let recipient=identity.accounts.find(x=>x.customerId===a.customerId)?.id;if(recipient)customEvent(recipient,'Un créneau vous attend',dayLabel(a.day)+' · '+matches.length+' possibilité(s) pour '+(a.participants||1)+' personne(s).',{alertId:a.id,category:'availability'})}}
if(changed)persist()}
function demoTools(){return `${pagebar('Simulation Partant')}<div class="section"><h1>Tester les deux côtés.</h1><p class="muted space">Ces outils appartiennent au prototype. Les paiements et les identités restent fictifs dans les deux modes.</p><div class="stack space">${[['presentation','Présentation · parcours épuré'],['demo','Test · comptes et incidents']].map(([id,label])=>`<button class="choice ${runtime.mode===id?'active':''}" data-action="prototype-mode" data-id="${id}"><span class="radio"></span>${label}</button>`).join('')}</div><p class="note space">Horloge : ${appNow().toLocaleString('fr-FR',{timeZone:'Europe/Paris'})} · Paris</p>${runtime.mode==='demo'?`<button class="pill full space" data-action="accounts">Choisir un compte fictif</button><button class="pill light full space" data-action="operations">Ouvrir l’espace équipe</button><button class="pill light full space" data-action="advance-clock" data-id="24">Avancer de 24 h</button><button class="pill light full space" data-action="advance-clock" data-id="1">Avancer d’une heure</button>`:''}<button class="textbtn full space" data-action="real-clock">Revenir à l’heure réelle</button><p class="small muted space">Les rappels et alertes sont recalculés à l’ouverture d’un écran. Avancer l’horloge peut terminer des séances ; revenir à l’heure réelle n’annule pas les opérations enregistrées.</p></div>`}
function hiddenTestTools(){let hide=runtime.mode!=='demo';document.querySelectorAll('[data-action="accounts"],[data-action="use-account"],[data-action="scenario"],[data-action="operations"],[data-action="open-operations"],[data-action="complete-demo"],[data-action="coach-complete"],[data-action="coach-no-show"],[data-action="simulate-verification"],[data-action="reset-demo"]').forEach(el=>{el.hidden=hide;el.style.display=hide?'none':''})}
configPage=function(){if(state.configSection==='schedule')return schedulePage();if(state.configSection==='documents')return documentsPage();return finalBase.configPage()};
coachSession=function(id){finalBase.coachSession(id);let b=bookingRecord(id);if(!b)return;let el=document.getElementById('modal-content');if(el&&state.auth?.role==='coach'&&b.coach===activeCoachId){el.innerHTML+='<div class="section">'+proposalPanel(b)+refundPanel(b)+(b.status==='confirmed'&&hoursUntil(b)>0?`<button class="pill light full space" data-action="propose-change" data-id="${b.id}">Proposer un autre horaire / lieu</button>`:'')+'</div>'}hiddenTestTools()};
render=function(){temporalMaintenance();let special={payment:paymentPage,'payment-lost':paymentLost,'account-settings':accountSettings,proposal:proposalPage,'prototype-tools':demoTools};if(special[state.screen]){view.innerHTML='<div class="screen">'+special[state.screen]()+'</div>';nav();if(state.auth?.role==='coach')document.getElementById('nav').innerHTML=coachNavigation();document.getElementById('nav').classList.toggle('hidden',['payment','payment-lost','prototype-tools'].includes(state.screen))}else finalBase.render();if(['account','bookings'].includes(state.screen)&&signedClient()){let attempts=identity.payments.filter(p=>p.owner===actorId()&&['pending','refused','interrupted','expired'].includes(p.status));if(attempts.length)view.innerHTML+='<div class="section"><h2>Séances à confirmer</h2>'+attempts.slice(-3).reverse().map(p=>`<button class="setting-row" data-action="resume-payment" data-id="${p.id}"><span>${dayLabel(p.selection.day)} · ${p.selection.time}<small>${esc(coaches[p.selection.coach].name)} · ${p.selection.quotedTotal} € · aucun débit</small></span>${ic('chevron')}</button>`).join('')+'</div>'}if(state.screen==='detail'){let b=findBooking();view.innerHTML+=`<div class="section">${proposalPanel(b)}${refundPanel(b)}</div>`}if(state.screen==='welcome'||state.screen==='account'||state.screen==='coach'&&state.coachTab==='settings')view.innerHTML+='<div class="section"><button class="textbtn full" data-action="prototype-tools">À propos de la simulation</button>'+ (state.auth?'<button class="setting-row" data-action="account-settings"><span>Mon compte & mes données</span>'+ic('chevron')+'</button>':'')+'</div>';if(state.screen==='login')view.innerHTML+='<div class="section"><button class="textbtn full" data-action="recover-login">Recevoir un nouveau code / aide connexion</button>'+(state.pendingCheckout?'<div class="note">Votre sélection est conservée. <button class="textbtn full" data-action="entry-signup">Créer mon compte pour continuer</button></div>':'')+'</div>';hiddenTestTools()};
act=function(a,d={}){if(runtime.mode!=='demo'&&['accounts','use-account','scenario','operations','open-operations','complete-demo','coach-complete','coach-no-show','confirm-no-show','simulate-verification','confirm-reset'].includes(a)){toast('Ces outils sont accessibles dans À propos de la simulation → Test.');return}switch(a){
case 'prototype-tools':closeModal();go('prototype-tools');return;
case 'operations':closeModal();go('operations');return;
case 'prototype-mode':runtime.mode=d.id==='demo'?'demo':'presentation';saveRuntime();render();return;
case 'calendar-week':state.dateWindows??={};state.dateWindows[d.target]=Number(d.id);if(d.target==='modal-day')dateModal(state.dateMode,state.modalDate);else render();return;
case 'time':state.day=todayIndex()+(d.id==='tomorrow'?1:0);state.period=d.id==='evening'?'evening':'all';state.hour='';render();return;
case 'switch-client':if(runtime.mode==='presentation'){state.entryRole='client';state.entryMode='login';go('login');return}break;
case 'pay':beginPayment();return;
case 'book':case 'join-group':case 'alert-book':state.paymentAttempt=null;if(state.auth?.role==='coach'&&runtime.mode==='presentation'){state.entryRole='client';state.entryMode='login';go('login');toast('Connectez-vous côté particulier pour réserver.');return}break;
case 'payment-result':settlePayment(d.id);return;
case 'retry-payment':{let old=identity.payments.find(p=>p.id===state.paymentAttempt);if(old&&old.status!=='paid')old.status='replaced';state.paymentAttempt=null;beginPayment();return}
case 'resume-payment':{let p=identity.payments.find(p=>p.id===d.id&&p.owner===actorId());if(!p||p.status==='paid')return;state.booking=clone(p.selection);state.paymentAttempt=p.id;go('checkout');return}
case 'payment-summary':go('checkout');return;
case 'payment-reselect':{let b=state.booking;state.paymentAttempt=null;if(b?.groupSessionId){state.groupId=b.groupSessionId;go('group-details')}else if(b){state.coach=b.coach;go('profile')}else go('explore');return}
case 'settle-refund':{if(runtime.mode!=='demo')return;let r=identity.refundLedger.find(x=>x.id===d.id);if(r?.status==='pending'){r.status='confirmed';r.confirmedAt=appNow().getTime();persist();render()}return}
case 'customer-settings':case 'account-settings':go('account-settings');return;
case 'export-account':if(state.auth)downloadText('partant-mes-donnees.json',JSON.stringify(ownExport(),null,2),'application/json');return;
case 'delete-account':showModal('Supprimer ce compte local ?',`<p>Vos coordonnées et messages personnels seront supprimés de cette démonstration. Les références des séances restent dans l’historique de vos interlocuteurs. Traitez d’abord toute séance confirmée.</p><button class="pill full space" data-action="confirm-delete-account">Supprimer mon compte de démonstration</button><button class="textbtn full space" data-action="close">Conserver mon compte</button>`);return;
case 'confirm-delete-account':deleteOwnAccount();return;
case 'recover-login':showModal('Retrouver votre accès',`<p>Le prototype utilise le code <strong>123456</strong>. Aucun e-mail n’est envoyé.</p><p class="space">Vérifiez votre adresse et le rôle choisi. Vous pouvez utiliser Alex (alex@example.test) côté particulier, ou Thomas (thomas@example.test) côté coach.</p><button class="pill full space" data-action="close">Revenir à la connexion</button>`);return;
case 'add-exception':showModal('Une journée particulière',`<form id="exception-form">${selectField('Date','day',futureDays(),todayIndex())}<label class="check-row"><input type="checkbox" name="closed">Fermé toute la journée</label><div class="split">${inputField('Début','start','09:00','time')}${inputField('Fin','end','18:00','time')}</div><p class="small muted">Cette plage remplace la semaine type pour cette date.</p><p id="exception-error" role="alert"></p><button class="pill full space">Enregistrer l’exception</button></form>`);return;
case 'remove-exception':delete cfg.exceptions[Number(d.id)];cfg.daysOff=cfg.daysOff.filter(x=>x!==Number(d.id));persist();render();return;
case 'review-dossier':reviewDossier(Number(d.id));return;
case 'propose-change':proposalForm(d.id);return;
case 'open-proposal':state.proposalId=d.id;closeModal();go('proposal');return;
case 'proposal-answer':answerProposal(d.id);return;
case 'proposal-withdraw':{let p=proposalFor(state.proposalId),b=p&&bookingRecord(p.bookingId);if(p?.status==='pending'&&state.auth?.role==='coach'&&b.coach===activeCoachId){p.status='withdrawn';customEvent(identity.accounts.find(x=>x.customerId===b.customerId)?.id,'Proposition retirée','Votre séance initiale reste confirmée.',{bookingId:b.id,proposalId:p.id});persist();render()}return}
case 'notification-open':{let n=myNotifications().find(n=>n.id===d.id);if(n?.kind==='custom'){n.read=true;persist();if(n.proposalId){state.proposalId=n.proposalId;go('proposal')}else if(n.alertId)go('alerts');else if(n.bookingId){state.selectedBooking=n.bookingId;if(state.auth?.role==='coach')coachSession(n.bookingId);else go('detail')}else{state.configSection='documents';go('config')}return}break}
case 'alert-places':state.editAlert=d.id;showModal('Les places qui vous correspondent',`<form id="alert-places-form">${inputField('Participants souhaités','participants',operations.alerts.find(x=>x.id===d.id)?.participants||1,'number','min="1" max="20" required')}<label class="check-row"><input type="checkbox" name="groupOnly" ${operations.alerts.find(x=>x.id===d.id)?.groupOnly?'checked':''}>Chercher uniquement des cours en groupe</label><p class="small muted space">À plusieurs, cette alerte recherche des places dans un cours collectif.</p><button class="pill full space">Enregistrer</button></form>`);return;
case 'advance-clock':if(runtime.mode!=='demo')return;runtime.clock=new Date(appNow().getTime()+Number(d.id)*3600000).toISOString();saveRuntime();state.day=todayIndex();state.coachDay=todayIndex();render();return;
case 'real-clock':runtime.clock=null;saveRuntime();state.day=todayIndex();state.coachDay=todayIndex();render();return;
case 'logout':case 'guest':state.pendingCheckout=null;break;
}finalBase.act(a,d);if(a==='join-group'&&state.booking?.sourceAlert){let alert=operations.alerts.find(x=>x.id===state.booking.sourceAlert);if(alert){state.booking.participants=alert.participants||1;render()}}};
document.addEventListener('submit',e=>{let form=e.target;if(!['weekly-form','exception-form','account-form','documents-form','document-review-form','proposal-form','alert-places-form'].includes(form.id))return;e.preventDefault();let f=new FormData(form);
if(form.id==='weekly-form'){try{let list=Array.from({length:7},(_,d)=>parseIntervals(f,d));if(!list.some(x=>x.length))throw Error('Ouvrez au moins une journée.');cfg.intervals=list;cfg.week=list.map(x=>!!x.length);cfg.weeklyConfigured=true;cfg.checks.schedule=true;state.configDirty=false;persist();render();toast('Semaine enregistrée. Les séances confirmées sont conservées.')}catch(err){document.getElementById('weekly-error').textContent=err.message}}
if(form.id==='exception-form'){let d=Number(f.get('day')),a=f.get('start'),b=f.get('end'),closed=f.has('closed');if(d<todayIndex()||d>=todayIndex()+90||!closed&&(!/^\d\d:\d\d$/.test(a||'')||!/^\d\d:\d\d$/.test(b||'')||mins(a)>=mins(b))){document.getElementById('exception-error').textContent='Vérifiez la date et les horaires.';return}(cfg.exceptions??={})[d]=closed?[]:[[a,b]];cfg.daysOff=cfg.daysOff.filter(x=>x!==d);if(closed)cfg.daysOff.push(d);persist();closeModal();render()}
if(form.id==='account-form'){let a=identity.accounts.find(x=>x.id===actorId()),email=String(f.get('email')||'').trim().toLowerCase(),name=String(f.get('name')||'').trim();if(!a||!name||!/^\S+@\S+\.\S+$/.test(email)||identity.accounts.some(x=>x.id!==a.id&&x.role===a.role&&x.email===email)){document.getElementById('account-error').textContent='Vérifiez le nom et une adresse e-mail disponible.';return}a.email=email;a.phone=String(f.get('phone')||'').trim();state.auth={...a};if(a.role==='coach'){if(cfg.name!==name){cfg.name=name;cfg.verified=false;cfg.published=false;if(cfg.documentCase)cfg.documentCase.status='draft'}cfg.notifications.reminder=f.has('reminders')}else{customer.name=name;customer.reminders=f.has('reminders');customer.alertNotifications=f.has('alerts')}persist();render();toast('Informations enregistrées dans la démo.')}
if(form.id==='documents-form'){if(state.auth?.role!=='coach')return;let documents=[0,1,2,3].map(i=>String(f.get('doc-'+i)||'').trim()),expires=String(f.get('expires')||'');if(documents.some(x=>!x)||expires<=parisISO())return toast('Complétez les quatre références et une validité future.');let history=dossier().history||[];history.push({status:'pending',date:parisISO()});cfg.documentCase={status:'pending',documents,expires,history};cfg.verified=false;cfg.published=false;persist();render()}
if(form.id==='document-review-form'){if(runtime.mode!=='demo')return;let p=ownerConfig(state.reviewCoach),d=dossier(p),status=f.get('status'),reason=String(f.get('reason')||'').trim();if(d.status!=='pending'||!['approved','correction','rejected'].includes(status)||!reason)return;d.status=status;d.reason=reason;d.history.push({status,reason,date:parisISO()});p.verified=status==='approved'&&d.expires>=parisISO();if(!p.verified)p.published=false;customEvent('coach-'+state.reviewCoach,'Votre dossier a été examiné',docLabels[status]+' · '+reason);persist();closeModal();render()}
if(form.id==='proposal-form'){let b=bookingRecord(state.proposalBooking);if(state.auth?.role!=='coach'||b?.coach!==activeCoachId)return;let g=b.groupSessionId&&groupById(f.get('group')),to=g?{groupSessionId:g.id,day:g.day,time:g.time,duration:g.duration,format:g.format,serviceName:g.name,serviceId:g.serviceId,location:clone(g.location),preparation:clone(g.preparation||{}),cancelHours:b.cancelHours}:b.groupSessionId?null:{day:Number(f.get('day')),time:String(f.get('time')),location:{name:String(f.get('place')||'').trim(),address:String(f.get('address')||'').trim()}},reason=String(f.get('reason')||'').trim(),error=document.getElementById('proposal-error');if(!to||!reason||!to.location.name||!to.location.address){error.textContent='Complétez la proposition et son motif.';return}let issue=proposalIssue(b,to);if(issue){error.textContent=issue;return}for(let p of pendingProposals(b))p.status='withdrawn';let p={id:'proposal-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6),bookingId:b.id,to,reason,status:'pending',fingerprint:JSON.stringify(bookingEventSnapshot(b)),locationFingerprint:JSON.stringify(locationFor(b)),createdAt:appNow().getTime()};identity.proposals.push(p);customEvent(identity.accounts.find(x=>x.customerId===b.customerId)?.id,'Votre coach propose un changement',reason,{bookingId:b.id,proposalId:p.id});persist();closeModal();state.proposalId=p.id;go('proposal')}
if(form.id==='alert-places-form'){let a=operations.alerts.find(x=>x.id===state.editAlert&&x.customerId===currentCustomerId),n=Number(f.get('participants'));if(!a||!Number.isInteger(n)||n<1||n>20)return;a.participants=n;a.groupOnly=f.has('groupOnly')||n>1;a.seenMatches=[];persist();closeModal();go('alerts')}
});
document.addEventListener('input',e=>{if(e.target.closest?.('#weekly-form'))state.configDirty=true});
state.day=Math.max(todayIndex(),state.day);state.coachDay=todayIndex();state.profileDay=todayIndex();

resetIdentityDemo=function(){identity.payments=[];identity.proposals=[];identity.reminderKeys=[];identity.refundLedger=[];state.pendingCheckout=null;finalBase.resetIdentityDemo()};

configSave=function(form){let was=cfg.verified;finalBase.configSave(form);if(was&&!cfg.verified&&cfg.documentCase){cfg.documentCase.status='draft';cfg.documentCase.reason='Votre profil a changé. Soumettez un dossier actualisé.';persist()}};
