from pathlib import Path
p=Path('work/partant.template.html')
s=p.read_text()
s=s.replace('href="evolution-produit-v2.md" target="_blank">Conception & parcours V2 ↗','href="priorite-1.md" target="_blank">Parcours & priorité 1 ↗')
s=s.replace('function updateRatings(){for(let c of coaches){let feedback=',"function updateRatings(){for(let c of coaches){c.baseRating??=Number(String(c.rating).replace(',','.'));c.baseReviews??=c.reviews;let feedback=")
s=s.replace("special[state.screen]()+'</div>';nav();document.getElementById('nav').classList.toggle('hidden',state.screen==='accounts');return", "special[state.screen]()+'</div>';nav();if(state.screen==='conversations'&&state.auth?.role==='coach')document.getElementById('nav').innerHTML=coachNavigation();document.getElementById('nav').classList.toggle('hidden',state.screen==='accounts');return")
s=s.replace("function act(a,d={}){switch(a)","function act(a,d={}){if(state.auth?.role==='coach'&&['book','join-group','alert-book'].includes(a)){go('accounts');toast('Choisissez un compte particulier pour réserver votre séance.');return}switch(a)")
s=s.replace("return list.sort((a,b)=>state.sort==='price'?displayPrice(a)-displayPrice(b):state.sort==='rating'?Number(b.rating.replace(',','.'))-Number(a.rating.replace(',','.')):a.dist-b.dist)}", "if(state.sort==='recommended'&&customer.done){let goals={'Me remettre en forme':['Remise en forme','Renforcement'],'Gagner en force':['Musculation','Renforcement'],'Me sentir mieux':['Yoga','Pilates'],'Préparer une course':['Running','Préparation compétition'],'Améliorer ma mobilité':['Mobilité'],'Perdre du poids':['Perte de poids']},tags=goals[customer.goal]||[],score=c=>tags.some(t=>[c.sport,...c.tags].includes(t))?1:0;return list.sort((a,b)=>score(b)-score(a)||a.dist-b.dist)}return list.sort((a,b)=>state.sort==='price'?displayPrice(a)-displayPrice(b):state.sort==='rating'?Number(b.rating.replace(',','.'))-Number(a.rating.replace(',','.')):a.dist-b.dist)}")
p.write_text(s)
