from pathlib import Path
p=Path('work/partant.template.html');s=p.read_text()
s=s.replace('function bookingCard(b){','function priorityOneBookingCard(b){',1).replace('function activity(){','function priorityOneActivity(){',1)
s=s.replace("function selectedService(id){return coachContext", "function selectedService(id){if(state.repeatOffer?.coach===id)return state.repeatOffer.service;return coachContext")
s=s.replace("state.booking=null;state.dateMode='';state.history=[];state.comp=[];", "state.booking=null;state.dateMode='';state.repeatOffer=null;state.changeDraft=null;state.history=[];state.comp=[];")
s=s.replace('notifications:notificationsPage};', 'notifications:notificationsPage,repeat:repeatPage,transfer:transferPage};')
s=s.replace('view.innerHTML=html;for(let c of coaches)', 'view.innerHTML=priorityTwoDecorate(html);for(let c of coaches)')
s=s.replace("function act(a,d={}){if(state.auth", "function act(a,d={}){if(priorityTwoAction(a,d))return;if(state.auth")
s=s.replace("customerId:b.customerId}}", "customerId:b.customerId,groupSessionId:b.groupSessionId||null,serviceName:b.serviceName,price:b.price}}")
s=s.replace("if(previous.status!==b.status&&b.status==='cancelled')kind='cancelled';", "if(previous.status!==b.status&&b.status==='cancelled')kind='cancelled';\n   else if(previous.groupSessionId!==(b.groupSessionId||null))kind='transferred';")
s=s.replace("else if(previous.refund!==next.refund)kind='refunded';\n   else if(previous.participants!==next.participants)kind='participants';", "else if(previous.participants!==next.participants)kind='participants';\n   else if(previous.refund!==next.refund)kind='refunded';")
s=s.replace("identity.eventSnapshots??=Object.fromEntries(state.bookings.map(b=>[b.id,bookingEventSnapshot(b)]));", "identity.eventSnapshots??=Object.fromEntries(state.bookings.map(b=>[b.id,bookingEventSnapshot(b)]));for(let b of state.bookings){let snap=identity.eventSnapshots[b.id];if(snap&&!('groupSessionId' in snap))Object.assign(snap,{groupSessionId:b.groupSessionId||null,serviceName:b.serviceName,price:b.price})}")
s=s.replace("rescheduled:'Séance déplacée',cancelled:", "rescheduled:'Séance déplacée',transferred:'Cours transféré',cancelled:")
old=next(line for line in s.splitlines() if line.startswith('function notificationDescription('))
new="""function notificationDescription(n){let who=state.auth?.role==='coach'?n.clientName:n.coachName,after=dayLabel(n.after.day)+' à '+n.after.time;return esc(who)+' · '+esc(n.serviceName)+'<br>'+(['rescheduled','transferred'].includes(n.kind)?'<span class="muted">Avant : '+dayLabel(n.before.day)+' à '+n.before.time+'</span><br><strong>Maintenant : '+after+'</strong>':after)+(n.kind==='participants'?'<br><strong>'+n.before.participants+' → '+n.after.participants+' places</strong>':n.after.participants>1?'<br>'+n.after.participants+' places':'')+(['cancelled','refunded','participants','transferred'].includes(n.kind)?'<br>Remboursements cumulés : '+n.after.refund+' €':'')+(n.kind==='transferred'&&n.after.price>n.before.price?'<br>Supplément simulé : '+(n.after.price-n.before.price)+' €':'')}"""
s=s.replace(old,new)
s=s.replace("· ${b.price} €</p><div class=\"note space\"><strong>${locationFor(b).name}", "· ${netPaid(b)} € net${b.groupSessionId?' · '+b.participants+' places':''}</p>${b.groupSessionId?financialPanel(b)+changesPanel(b):''}<div class=\"note space\"><strong>${locationFor(b).name}")
s=s.replace('href="priorite-1.md" target="_blank">Parcours & priorité 1 ↗','href="priorite-2.md" target="_blank">Parcours & priorité 2 ↗')
code=Path('work/priority-two.js').read_text().replace(".filter(time=>!conflictsWithClient(day,time,s.duration))", ".filter(time=>(day>b.day||mins(time)>mins(b.time))&&!conflictsWithClient(day,time,s.duration))")
s=s.replace('\nsyncAllCoaches();\n\nrender();', '\n'+code+'\nsyncAllCoaches();\n\nrender();')
p.write_text(s)
