// Partant v2 — guided entry, customer preferences and coach operations.
let v2saved={};try{v2saved=JSON.parse(localStorage.getItem('partant-v2')||'{}')}catch(e){}
const cfg=Object.assign({name:'Thomas Martin',sport:'Préparation physique',bio:coaches[0].bio,cert:coaches[0].cert,langs:'Français, anglais',experience:8,services:[{id:'solo',name:'Coaching individuel',kind:'Individuel',duration:60,price:saved.prices?.[0]||50,active:true},{id:'duo',name:'Coaching duo',kind:'Duo',duration:60,price:(saved.prices?.[0]||50)+20,active:true}],formats:['Parc','Studio','Domicile'],place:'Square Maurice-Gardette',address:'2 rue du Général-Blaise, 75011 Paris',studio:'Studio Voltaire',studioAddress:'22 rue de la Roquette, 75011 Paris',radius:3,travelFee:0,weeklyConfigured:false,week:[true,true,true,true,true,true,false],start:'09:00',end:'21:00',breakStart:'12:00',breakEnd:'14:00',useBreak:false,buffer:0,notice:2,horizon:14,daysOff:[],cancelHours:24,published:true,verified:true,payoutReady:true,notifications:{booking:true,changes:true,reminder:true,marketing:false},checks:{profile:true,offers:true,places:true,schedule:true},clientNotes:{},coachMessages:{},privateEvents:[]},v2saved.cfg||{});
const customer=Object.assign({name:'Alex',sport:'Tout',goal:'Me remettre en forme',level:'Je reprends',city:'Paris 11e',budget:80,distance:10,format:'Tous',moment:'Libre',done:false,reminders:true},v2saved.customer||{});
state.auth=v2saved.auth||null;state.coachTab='agenda';state.onboardStep=0;state.entryRole='client';state.entryMode='login';state.configSection='profile';state.wizard=false;state.screen=state.auth?(state.auth.role==='coach'?'coach':'explore'):'welcome';
function syncCoach(){let c=coaches[0];Object.assign(c,{name:cfg.name,sport:cfg.sport,bio:cfg.bio,cert:cfg.cert,langs:cfg.langs,years:cfg.experience,formats:[...cfg.formats],place:cfg.place,address:cfg.address});}
syncCoach();
function persist(){legacyPersist();try{localStorage.setItem('partant-v2',JSON.stringify({cfg,customer,auth:state.auth}))}catch(e){}}
function servicesFor(id){return id===0?cfg.services.filter(s=>s.active):[{id:'solo',name:'Coaching individuel',kind:'Individuel',duration:60,price:price(coaches[id]),active:true},{id:'duo',name:'Coaching duo',kind:'Duo',duration:60,price:price(coaches[id])+20,active:true}]}
function primaryService(id){return servicesFor(id)[0]||{id:'none',name:'Aucune offre',duration:60,price:0,kind:'Individuel'}}
function selectedService(id){return ['setup','checkout'].includes(state.screen)&&state.booking?.coach===id?(servicesFor(id).find(s=>s.id===state.booking.serviceId)||primaryService(id)):primaryService(id)}
function clockText(n){return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function allSlots(c,d){if(c.id!==0||!cfg.weeklyConfigured)return legacyAllSlots(c,d);if(!cfg.week[d%7]||cfg.daysOff.includes(d))return [];let result=[],dur=selectedService(0).duration;for(let t=mins(cfg.start);t+dur<=mins(cfg.end);t+=30){if(!cfg.useBreak||t+dur<=mins(cfg.breakStart)||t>=mins(cfg.breakEnd))result.push(clockText(t))}return result}
function overlaps(t,d,t2,d2,buffer=0){return t<t2+d2+buffer&&t+d+buffer>t2}
function avail(c,d,ignoreId){let s=selectedService(c.id);if(c.id===0&&(!cfg.published||!cfg.verified||!cfg.payoutReady||!servicesFor(0).length||!cfg.formats.length||d>=cfg.horizon||cfg.daysOff.includes(d)))return [];let buffer=c.id===0?cfg.buffer:0;return allSlots(c,d).filter(t=>!state.closed.includes(key(c.id,d,t))&&(c.id!==0||d*24+(mins(t)-480)/60>=cfg.notice)&&!state.bookings.some(b=>b.id!==ignoreId&&['confirmed','completed','no-show'].includes(b.status)&&b.coach===c.id&&b.day===d&&overlaps(mins(t),s.duration,mins(b.time),b.duration||60,buffer))&&!(c.id===0&&cfg.privateEvents.some(e=>e.day===d&&overlaps(mins(t),s.duration,mins(e.start),mins(e.end)-mins(e.start),buffer))))}
function endTime(t,duration=60){return t?clockText(mins(t)+duration):'—'}
function locationFor(b){if(b.location)return b.location;let c=coaches[b.coach];if(b.format==='Domicile')return {name:'À votre domicile',address:b.home||'Adresse à préciser'};if(b.format==='Visio')return {name:'En visioconférence',address:'Lien disponible dans le détail de votre séance'};if(b.coach===0&&b.format==='Studio')return {name:cfg.studio,address:cfg.studioAddress};if(b.format===c.formats[0]||b.format==='Parc')return {name:c.place,address:c.address};return {name:cfg.studio,address:cfg.studioAddress}}
function bookingPrice(b){let s=servicesFor(b.coach).find(s=>s.id===b.serviceId)||servicesFor(b.coach).find(s=>s.kind===b.kind)||primaryService(b.coach);return s.price+(b.coach===0&&b.format==='Domicile'?cfg.travelFee:0)}
function startBooking(id,time,day){let c=coaches[id],s=primaryService(id);state.booking={coach:id,day:day??state.day,time,kind:s.kind,serviceId:s.id,serviceName:s.name,duration:s.duration,format:state.format!=='Tous'&&c.formats.includes(state.format)?state.format:c.formats[0],home:'',payment:'apple',goal:customer.goal};go('setup')}
function cancellationDeadline(b){let d=new Date(base);d.setDate(d.getDate()+b.day);d.setHours(...b.time.split(':').map(Number));d=new Date(d.getTime()-(b.cancelHours??24)*3600000);return d.toLocaleDateString('fr-FR',{day:'numeric',month:'long'})+' à '+clockText(d.getHours()*60+d.getMinutes())}
function applyPreferences(){Object.assign(state,{sport:customer.sport,city:customer.city,maxPrice:customer.budget,maxDist:customer.distance,format:customer.format,query:'',day:0,hour:'',period:customer.moment==='Le soir'?'evening':'all'});if(customer.moment==='Demain')state.day=1;}
if(state.auth?.role==='client'&&customer.done)applyPreferences();
function welcome(){return `<div class="entry-hero"><div class="wordmark">partant</div><div class="eyebrow">LE SPORT COMMENCE PAR UNE RENCONTRE.</div><h1>Un coach.<br>Votre rythme.</h1><p>Le bon accompagnement,<br>au bon moment.</p><div class="entry-portraits"><div class="photo p0"></div><div class="photo p1"></div><div class="photo p2"></div></div></div><div class="sheet section"><h2 style="margin-bottom:16px">Bienvenue chez Partant.</h2><p class="muted subhead">Comment voulez-vous nous rejoindre ?</p><button class="choice ${state.entryRole==='client'?'active':''}" data-action="entry-role" data-id="client"><span class="radio"></span><span><strong>Je veux bouger</strong><small>Trouver un coach et réserver mes séances</small></span></button><button class="choice ${state.entryRole==='coach'?'active':''}" data-action="entry-role" data-id="coach"><span class="radio"></span><span><strong>Je suis coach</strong><small>Développer mon activité, simplement</small></span></button><button class="pill full space" data-action="entry-next">Me connecter ${ic('arrow','sm')}</button><button class="textbtn full" data-action="entry-signup">Créer mon compte</button><button class="textbtn full muted" data-action="guest">Explorer d’abord</button><p class="small muted" style="text-align:center;margin-top:12px">Prototype · aucune authentification réelle</p></div>`}
function login(){return `${pagebar(state.entryRole==='coach'?'Espace coach':'Espace particulier')}<div class="section"><div class="wordmark">partant</div><h1 style="margin:40px 0 12px">${state.entryMode==='signup'?'Votre prochaine étape.':'Heureux de vous revoir.'}</h1><p class="muted">Un code pour vous connecter.<br>Un compte pour retrouver vos séances.</p><form id="entry-form" class="space">${state.entryMode==='signup'?'<label class="field">Votre prénom<input name="name" autocomplete="given-name" placeholder="Alex" required maxlength="40"></label>':''}<label class="field">Adresse e-mail de démonstration<input type="email" name="email" value="${state.entryRole==='coach'?'thomas':'alex'}@example.test" required autocomplete="off"></label><button class="pill full">Continuer avec mon e-mail</button></form><div class="note space">Démo : aucun e-mail ne sera envoyé. Le code à saisir à l’étape suivante est <strong>123456</strong>. N’utilisez pas de mot de passe réel.</div><button class="textbtn full space" data-action="guest">Continuer sans compte</button><p class="small muted space">Vos essais restent dans ce navigateur. Aucun compte n’est créé auprès d’un service externe.</p></div>`}
function codeScreen(){return `${pagebar('Connexion')}<div class="section"><div class="eyebrow muted">UNE DERNIÈRE ÉTAPE</div><h1 style="margin:20px 0 12px">C’est bien vous.</h1><p class="muted">Dans la version réelle, un code serait envoyé à votre adresse e-mail.</p><form id="code-form" class="space"><label class="field">Code de démonstration<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="123456" required autocomplete="off" style="font-size:28px;letter-spacing:10px;text-align:center;height:66px"></label><p id="code-error" role="alert" class="small"></p><button class="pill full space">${state.entryMode==='signup'?'Créer mon espace de démonstration':'Me connecter à la démo'}</button></form><div class="note space">Code de test : <strong>123456</strong><br>Aucun code n’a été envoyé.</div><button class="textbtn full space" data-action="back">Changer d’adresse e-mail</button></div>`}
function selectField(label,name,values,current){return `<label class="field">${label}<select name="${name}">${values.map(v=>{let a=Array.isArray(v)?v:[v,v];return `<option value="${esc(a[0])}" ${String(current)===String(a[0])?'selected':''}>${esc(a[1])}</option>`}).join('')}</select></label>`}
function inputField(label,name,value,type='text',extra=''){return `<label class="field">${label}<input type="${type}" name="${name}" value="${esc(value??'')}" ${extra}></label>`}
function onboarding(){let i=state.onboardStep;let parts=[`<h1>Qu’est-ce qui<br>vous met en mouvement ?</h1><p class="muted subhead space">Un point de départ, pas une case.</p>${selectField('Votre pratique','sport',['Tout','Préparation physique','Running','Pilates','Musculation','Boxe','Yoga','Mobilité','Remise en forme','Tennis','Natation'],customer.sport)}${selectField('Votre objectif','goal',['Me remettre en forme','Gagner en force','Me sentir mieux','Préparer une course','Améliorer ma mobilité','Découvrir une pratique','Perdre du poids'],customer.goal)}${selectField('Vous en êtes où ?','level',['Je débute','Je reprends','Je pratique régulièrement'],customer.level)}`,`<h1>Près de vous.<br>Dans votre budget.</h1><p class="muted subhead space">Vous pourrez tout ajuster ensuite.</p>${selectField('Votre secteur','city',['Paris 11e','Paris','Lyon','Bordeaux','Marseille'],customer.city)}${selectField('Votre budget maximum par séance','budget',[[40,'Jusqu’à 40 €'],[50,'Jusqu’à 50 €'],[60,'Jusqu’à 60 €'],[80,'Jusqu’à 80 €']],customer.budget)}${selectField('Distance maximale','distance',[[1,'1 km'],[2,'2 km'],[5,'5 km'],[10,'10 km']],customer.distance)}<p class="small muted">Paris est la ville pilote de la démo. Pour les autres villes, la visio reste accessible.</p>`,`<h1>Et dans votre<br>quotidien ?</h1><p class="muted subhead space">On s’adapte à vous, pas l’inverse.</p>${selectField('Le lieu qui vous convient','format',[['Tous','Je suis flexible'],['Parc','En extérieur'],['Studio','Au studio'],['Domicile','Chez moi'],['Visio','En visio']],customer.format)}${selectField('Votre prochain moment','moment',['Libre','Le soir','Demain'],customer.moment)}<div class="note"><strong>Votre point de départ</strong><p>${esc(customer.sport==='Tout'?'Toutes les pratiques':customer.sport)} · ${esc(customer.goal)}<br>${esc(customer.city)} · jusqu’à ${customer.budget} €</p></div>`];return `${pagebar('Votre rythme')}<div class="section"><div class="onboard-progress" aria-label="Étape ${i+1} sur 3">${[0,1,2].map(n=>`<span class="${n<=i?'done':''}"></span>`).join('')}</div><p class="eyebrow muted" style="margin:20px 0">${i+1} / 3 · ${['VOS ENVIES','VOS REPÈRES','VOTRE MOMENT'][i]}</p><form id="onboard-form">${parts[i]}<button class="pill full space">${i===2?'Découvrir mes coachs':'Continuer'} ${ic('arrow','sm')}</button></form><button class="textbtn full" data-action="skip-onboard">Passer pour le moment</button></div>`}
function setup(){let b=state.booking,c=coaches[b.coach],services=servicesFor(c.id);return `${pagebar('Votre séance')}<div class="section"><div class="eyebrow muted">01 — VOTRE SÉANCE</div><h1 style="margin:12px 0 24px">Un moment pour vous.</h1>${summaryPerson(b)}<h2 class="space subhead">Votre accompagnement</h2>${services.map(s=>`<button class="choice ${b.serviceId===s.id?'active':''}" data-action="select-service" data-id="${s.id}"><span class="radio"></span><span class="grow"><strong>${esc(s.name)}</strong><small>${s.kind} · ${s.duration} minutes</small></span><strong>${s.price} €</strong></button>`).join('')}<button class="setting-row" data-action="booking-date"><span class="row">${ic('calendar')}<span><strong>${b.time?dayLabel(b.day):'Choisir un créneau'}</strong><small>${b.time?b.time+' – '+endTime(b.time,b.duration):'La durée a changé : choisissez votre heure'} · ${b.duration} min</small></span></span>${ic('chevron')}</button><h2 class="space subhead">Où on se retrouve ?</h2>${c.formats.map(f=>`<button class="choice ${b.format===f?'active':''}" data-action="format" data-id="${f}"><span class="radio"></span><span class="grow"><strong>${f==='Domicile'?'Chez vous':f==='Visio'?'En visio':f==='Parc'?'En extérieur':'Au studio'}</strong><small>${f==='Domicile'?'Rayon de '+(c.id===0?cfg.radius:3)+' km · '+(c.id===0&&cfg.travelFee?'+ '+cfg.travelFee+' €':'déplacement inclus'):locationFor({...b,format:f}).name}</small></span></button>`).join('')}${b.format==='Domicile'?inputField('Adresse fictive du rendez-vous','home',b.home,'text','id="home-address" placeholder="10 rue de la Roquette, Paris 11e"')+`<label class="field"><span class="row"><input id="zone-confirm" type="checkbox" style="width:20px;height:20px">Je confirme être dans le rayon de déplacement indiqué.</span></label>`:''}<label class="field space">Votre objectif pour cette séance<textarea id="session-goal" maxlength="300">${esc(b.goal||customer.goal)}</textarea></label><p class="small muted">Quelques mots suffisent. Évitez les informations médicales ou sensibles dans ce prototype.</p><div class="note space">Annulation gratuite jusqu’à ${c.id===0?cfg.cancelHours:24} h avant.</div></div><div class="sticky-cta"><div><strong style="font-size:22px">${bookingPrice(b)} €</strong><p class="small muted">Prix total${b.kind==='Duo'?' pour deux':''}</p></div><button class="pill" data-action="checkout" ${!b.time?'disabled':''}>Continuer ${ic('arrow','sm')}</button></div>`}
function doPay(){let b=state.booking;b.cancelHours=b.coach===0?cfg.cancelHours:24;if(!avail(coaches[b.coach],b.day).includes(b.time)){showModal('Ce créneau n’est plus disponible','<p>Votre coach a modifié son planning ou son offre. Choisissez un nouveau créneau.</p><button class="pill full space" data-action="booking-date">Voir les disponibilités</button>');return}if(state.bookings.some(x=>x.status==='confirmed'&&x.day===b.day&&overlaps(mins(x.time),x.duration||60,mins(b.time),b.duration))){toast('Une autre séance est déjà prévue à cette heure.');return}let booked={...b,id:'pt-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),price:bookingPrice(b),location:locationFor(b),status:'confirmed',clientName:customer.name||'Alex'};state.bookings.push(booked);state.selectedBooking=booked.id;persist();state.history=[];go('confirmation')}
const coachSections=[['profile','user','Votre profil','La personne derrière le coach'],['offers','strength','Séances & tarifs','Durées, individuel, duo'],['places','pin','Lieux & déplacements','Adresses, rayon, frais éventuels'],['schedule','calendar','Disponibilités','Semaine type, pauses et absences'],['rules','shield','Réservation & annulation','Délais et temps entre séances'],['documents','shield','Documents & vérification','Identité, diplômes, assurance'],['payout','wallet','Paiements & versements','Commission et coordonnées professionnelles'],['notifications','message','Notifications','Les nouvelles qui comptent'],['calendars','calendar','Agendas connectés','Google, Apple et Outlook']];
function configStatus(id){if(id==='documents')return cfg.verified?'Vérifié · démo':'À compléter';if(id==='payout')return cfg.payoutReady?'Activé · démo':'À compléter';return cfg.checks[id]?'Prêt':''}
function coachNavigation(){return [['agenda','calendar','Agenda'],['clients','user','Clients'],['activity','wallet','Activité'],['settings','filter','Réglages']].map(([id,i,t])=>`<button class="navitem ${state.coachTab===id?'active':''}" data-action="coach-tab" data-id="${id}" ${state.coachTab===id?'aria-current="page"':''}>${ic(i)}${t}</button>`).join('')}
function publicationReady(){return Object.values(cfg.checks).every(Boolean)&&cfg.verified&&cfg.payoutReady&&cfg.services.some(s=>s.active)&&cfg.formats.length>0}
function checklist(){let items=[['profile','Présentez-vous',cfg.checks.profile],['offers','Créez votre offre',cfg.checks.offers],['places','Choisissez vos lieux',cfg.checks.places],['schedule','Ouvrez votre planning',cfg.checks.schedule],['documents','Vérifiez votre profil',cfg.verified],['payout','Activez vos versements',cfg.payoutReady]];return `<div class="section"><div class="eyebrow muted">VOTRE ACTIVITÉ PREND FORME</div><h1 style="margin:14px 0">Faisons place<br>à vos prochains clients.</h1><p class="muted">${items.filter(x=>x[2]).length} étapes sur 6 prêtes. Avancez à votre rythme : tout est enregistré.</p><div class="space">${items.map(([id,t,done],i)=>`<button class="setting-row" data-action="config" data-id="${id}"><span class="row"><span class="step-circle ${done?'done':''}">${done?'✓':i+1}</span><span>${t}</span></span>${ic('chevron')}</button>`).join('')}</div><button class="pill full space" data-action="publish" ${!publicationReady()?'disabled':''}>${cfg.published?'Voir mon profil public':'Publier mon profil de démonstration'}</button><p class="small muted space">Les contrôles et versements sont simulés. La publication rend votre offre visible dans ce prototype uniquement.</p></div>`}
function coachHome(){let tab=state.coachTab;let booked=state.bookings.filter(b=>b.coach===0&&b.status==='confirmed'),d=state.coachDay;let head=`<div class="prohead"><div class="row between"><div class="wordmark">partant <span class="pro-label">coach</span></div><button class="iconbtn" data-action="switch-client" aria-label="Passer côté client">${ic('user')}</button></div><h1>${tab==='agenda'?'Votre prochain mouvement.':tab==='clients'?'Les liens qui comptent.':tab==='activity'?'Votre activité, au clair.':'Tout, à votre façon.'}</h1><p>${tab==='agenda'?dayLabel(d):tab==='clients'?'Un suivi simple, une relation qui dure.':tab==='activity'?'Séances, encaissements et versements.':'Votre offre. Vos règles. Votre rythme.'}</p></div>`;
if(tab==='settings')return head+`<div class="sheet section"><button class="publication ${cfg.published?'on':''}" data-action="publication"><span><strong>${cfg.published?'Votre profil est en ligne':'Votre profil est en pause'}</strong><small>${cfg.published?'Les clients peuvent réserver vos disponibilités':'Les nouvelles réservations sont suspendues'}</small></span><span class="toggle ${cfg.published?'on':''}"></span></button><button class="setting-row" data-action="coach-wizard"><span>Ma checklist de mise en ligne</span>${ic('chevron')}</button>${coachSections.map(([id,ico,t,desc])=>`<button class="setting-row" data-action="config" data-id="${id}"><span class="row">${ic(ico)}<span><strong>${t}</strong><small>${desc}</small></span></span><span class="small muted">${configStatus(id)} ${ic('chevron','sm')}</span></button>`).join('')}<button class="pill light full space" data-action="profile" data-id="0">Prévisualiser mon profil</button><button class="textbtn full" data-action="logout">Me déconnecter</button></div>`;
if(tab==='clients')return head+`<div class="sheet section"><div class="searchbar" style="margin:0 0 20px">${ic('search','sm')}<input aria-label="Rechercher un client" id="client-search" placeholder="Rechercher un client" oninput="filterClients(this.value)"></div><div id="client-list">${clientList()}</div><p class="small muted space">Les profils ci-dessous sont fictifs. Vos nouveaux clients réservés apparaissent ici.</p></div>`;
if(tab==='activity')return head+activity();
let dayBookings=booked.filter(b=>b.day===d),slotTimes=allSlots(coaches[0],d),blocked=cfg.privateEvents.filter(e=>e.day===d);return head+`<div class="sheet section">${!cfg.published?'<div class="note subhead">Votre vitrine est en pause. Les réservations existantes restent confirmées.</div>':''}<div class="row between subhead"><h2>Votre agenda</h2><button class="textbtn" data-action="private-event">+ Indisponibilité</button></div>${dateStrip(d,'coach-day')}<div class="row between space"><strong>${dayBookings.length} séance${dayBookings.length>1?'s':''} prévue${dayBookings.length>1?'s':''}</strong><button class="textbtn" data-action="config" data-id="schedule">Configurer</button></div>${dayBookings.map(b=>`<button class="agenda-booking" data-action="coach-session" data-id="${b.id}"><time>${b.time}<small>${b.duration||60} min</small></time><span class="grow"><strong>${esc(b.clientName||'Alex')}</strong><small>${esc(b.serviceName||b.kind)} · ${b.format}</small></span>${ic('chevron')}</button>`).join('')}${blocked.map(e=>`<button class="agenda-block" data-action="delete-private" data-id="${e.id}"><strong>${e.start} – ${e.end}</strong><span>${esc(e.title)}</span>${ic('close','sm')}</button>`).join('')}<h3 class="space subhead">Disponibilités proposées</h3><div class="slots">${slotTimes.map(t=>{let occupied=dayBookings.some(b=>overlaps(mins(t),primaryService(0).duration,mins(b.time),b.duration||60,cfg.buffer));let free=avail(coaches[0],d).includes(t),manual=state.closed.includes(key(0,d,t));return `<button class="slot ${free?'':'unavailable'}" data-action="coach-toggle" data-time="${t}" ${occupied||(!free&&!manual)?'disabled':''} aria-label="${t} · ${occupied?'réservé':free?'ouvert':manual?'fermé manuellement':'indisponible selon vos règles'}">${t}${manual?' ×':''}</button>`}).join('')||'<p class="muted">Aucune plage ouverte ce jour.</p>'}</div><p class="small muted space">Touchez une heure pour la fermer ou la rouvrir. Les temps de déplacement et les séances déjà réservées sont protégés.</p><div class="note space row">${ic('clock')}<span>${primaryService(0).duration} min par séance · ${cfg.buffer} min entre séances · réservation ${cfg.notice} h minimum à l’avance.</span></div></div>`}
function clientData(){let clients=[{id:'alex',name:customer.name||'Alex',goal:customer.goal,level:customer.level},{id:'julie',name:'Julie Renard',goal:'Retrouver une routine sportive',level:'Pratique régulière'},{id:'mehdi',name:'Mehdi Laurent',goal:'Préparer un 10 km',level:'Reprise progressive'}];return clients}
function clientList(query=''){return clientData().filter(c=>c.name.toLowerCase().includes(query.toLowerCase())).map(c=>`<button class="setting-row" data-action="client" data-id="${c.id}"><span class="row"><span class="initial">${esc(c.name[0])}</span><span><strong>${esc(c.name)}</strong><small>${esc(c.goal)}</small></span></span>${ic('chevron')}</button>`).join('')||'<div class="empty"><h3>Aucun client correspondant</h3><p>Essayez un autre prénom.</p></div>'}
function filterClients(q){document.getElementById('client-list').innerHTML=clientList(q)}
function clientDetail(){let c=clientData().find(c=>c.id===state.clientId)||clientData()[0];let sessions=c.id==='alex'?state.bookings.filter(b=>b.coach===0):[];return `${pagebar('Fiche client')}<div class="section"><div class="initial large">${esc(c.name[0])}</div><h1 class="space">${esc(c.name)}</h1><p class="muted">${esc(c.level)}</p><div class="note space"><strong>Son objectif</strong><p>${esc(c.goal)}</p></div><button class="pill full space" data-action="coach-chat" data-id="${c.id}">${ic('message','sm')} Écrire à ${esc(c.name.split(' ')[0])}</button><h2 class="space subhead">Notes privées du coach</h2><form id="client-note-form"><label class="field">Repères utiles pour les prochaines séances<textarea name="note" maxlength="1200" placeholder="Préférences de séance, matériel, prochain objectif…">${esc(cfg.clientNotes[c.id]||'')}</textarea></label><p class="small muted">Notes visibles uniquement dans cet espace coach simulé. Ne saisissez pas de données médicales ou sensibles.</p><button class="pill light full space">Enregistrer mes notes</button></form><h2 class="space subhead">Historique des séances</h2>${sessions.length?sessions.map(b=>`<button class="setting-row" data-action="coach-session" data-id="${b.id}"><span>${dayLabel(b.day)} · ${b.time}<small>${b.status==='confirmed'?'À venir':b.status==='completed'?'Terminée':b.status==='no-show'?'Absent':'Annulée'} · ${b.duration||60} min</small></span><strong>${b.price} €</strong></button>`).join(''):'<p class="muted">Aucune séance enregistrée dans cette démo.</p>'}</div>`}
function activity(){let sales=state.bookings.filter(b=>b.coach===0),retained=sales.filter(b=>b.status!=='cancelled'||!b.refund),gross=retained.reduce((s,b)=>s+b.price,0),earned=retained.filter(b=>['completed','no-show','cancelled'].includes(b.status)).reduce((s,b)=>s+b.price*.85,0),euros=n=>n.toLocaleString('fr-FR',{style:'currency',currency:'EUR'});return `<div class="sheet section"><p class="eyebrow muted">NET COACH PRÉVISIONNEL</p><div class="revenue-big">${euros(gross*.85)}</div><div class="stat-pair"><div><strong>${retained.length}</strong><small>Séances vendues</small></div><div><strong>${euros(earned)}</strong><small>Éligible après séance · démo</small></div></div><div class="receipt"><div class="row between"><span>Montant des séances</span><strong>${euros(gross)}</strong></div><div class="row between"><span>Commission Partant · 15 %</span><strong>− ${euros(gross*.15)}</strong></div></div><button class="pill light full" data-action="export-sales">Télécharger le relevé CSV ${ic('arrow','sm')}</button><h2 class="space subhead">Dernières opérations</h2>${sales.length?sales.slice().reverse().map(b=>`<button class="setting-row" data-action="coach-session" data-id="${b.id}"><span>${esc(b.clientName||'Alex')} · ${dayLabel(b.day)}<small>${b.status==='cancelled'?'Annulée · remboursement '+(b.refund||0)+' €':b.status==='completed'?'Séance terminée':'Réservation enregistrée'}</small></span><strong>${euros(b.price)}</strong></button>`).join(''):'<div class="note">Vos ventes et remboursements apparaîtront ici dès la première réservation.</div>'}<button class="setting-row" data-action="config" data-id="payout"><span>Gérer mes versements<small>${cfg.payoutReady?'Compte de test activé':'Activation nécessaire'}</small></span>${ic('chevron')}</button><p class="small muted space">Simulation : aucun encaissement, virement ou document fiscal réel. Les règles de reversement définitives restent à valider.</p></div>`}
function configPage(){let id=state.configSection,entry=coachSections.find(x=>x[0]===id),body='';if(id==='profile')body=`${inputField('Nom public','name',cfg.name,'text','required maxlength="60"')}${selectField('Discipline principale','sport',['Préparation physique','Running','Pilates','Musculation','Boxe','Yoga','Mobilité'],cfg.sport)}<label class="field">Votre approche<textarea name="bio" required maxlength="900">${esc(cfg.bio)}</textarea></label>${inputField('Années d’expérience','experience',cfg.experience,'number','min="0" max="60" required')}${inputField('Diplômes et certifications','cert',cfg.cert,'text','required maxlength="160"')}${inputField('Langues parlées','langs',cfg.langs,'text','required maxlength="100"')}<p class="note">Portrait de démonstration conservé. La vérification des pièces est indépendante du texte de votre profil.</p>`;
if(id==='offers')body=`<p class="muted subhead">Des offres compréhensibles, avec un prix total et une durée précise.</p>${cfg.services.map(s=>`<div class="offer-row"><div class="row between"><strong>${esc(s.name)}</strong><span class="badge">${s.active?'Active':'En pause'}</span></div><p class="muted">${s.duration} min · ${s.kind} · ${s.price} €</p><div class="row between"><button type="button" class="textbtn" data-action="edit-service" data-id="${s.id}">Modifier</button><button type="button" class="textbtn" data-action="toggle-service" data-id="${s.id}">${s.active?'Mettre en pause':'Activer'}</button></div></div>`).join('')}<button type="button" class="pill light full" data-action="new-service">${ic('plus','sm')} Créer une séance</button><div class="note space">La première offre active est celle présentée dans les résultats. Les réservations déjà payées conservent leur prix et leur durée.</div>`;
if(id==='places')body=`<fieldset class="field"><legend>Formats proposés</legend>${['Parc','Studio','Domicile','Visio'].map(f=>`<label class="check-row"><input type="checkbox" name="formats" value="${f}" ${cfg.formats.includes(f)?'checked':''}>${f}</label>`).join('')}</fieldset>${inputField('Lieu extérieur / lieu principal','place',cfg.place,'text','required maxlength="100"')}${inputField('Adresse du lieu principal','address',cfg.address,'text','required maxlength="180"')}${inputField('Nom du studio','studio',cfg.studio,'text','maxlength="100"')}${inputField('Adresse du studio','studioAddress',cfg.studioAddress,'text','maxlength="180"')}${selectField('Rayon de déplacement à domicile','radius',[[1,'1 km'],[3,'3 km'],[5,'5 km'],[10,'10 km']],cfg.radius)}${inputField('Supplément déplacement à domicile (€)','travelFee',cfg.travelFee,'number','min="0" max="30" required')}<p class="note">Le supplément est présenté avant paiement. Le rayon et les adresses restent fictifs : la vérification géographique n’est pas connectée.</p>`;
if(id==='schedule')body=`<h3 class="subhead">Votre semaine type</h3><fieldset class="week-checks"><legend class="small muted">Jours travaillés</legend>${['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map((t,i)=>`<label><input type="checkbox" name="week" value="${i}" ${cfg.week[i]?'checked':''}><span>${t}</span></label>`).join('')}</fieldset><div class="split">${inputField('Début','start',cfg.start,'time','required')}${inputField('Fin','end',cfg.end,'time','required')}</div><label class="check-row"><input type="checkbox" name="useBreak" ${cfg.useBreak?'checked':''}>Prévoir une pause quotidienne</label><div class="split">${inputField('Début de pause','breakStart',cfg.breakStart,'time','required')}${inputField('Fin de pause','breakEnd',cfg.breakEnd,'time','required')}</div><h3 class="space subhead">Absences exceptionnelles</h3><fieldset class="absence-grid"><legend class="small muted">Septembre 2026 · cochez les jours fermés</legend>${days.map((d,i)=>`<label><input type="checkbox" name="daysOff" value="${i}" ${cfg.daysOff.includes(i)?'checked':''}><span>${d.short} ${d.num}</span></label>`).join('')}</fieldset><div class="note space">Le planning public sera recalculé par pas de 30 min, selon la durée de l’offre. Les réservations confirmées sont conservées, même si vous fermez ensuite une journée.</div>`;
if(id==='rules')body=`${selectField('Temps entre deux séances','buffer',[[0,'Aucun'],[15,'15 minutes'],[30,'30 minutes'],[60,'60 minutes']],cfg.buffer)}${selectField('Délai minimum avant réservation','notice',[[1,'1 heure'],[2,'2 heures'],[6,'6 heures'],[12,'12 heures'],[24,'24 heures']],cfg.notice)}${selectField('Ouverture du planning','horizon',[[7,'7 jours à l’avance'],[14,'14 jours à l’avance']],cfg.horizon)}${selectField('Annulation gratuite jusqu’à','cancelHours',[[12,'12 heures avant'],[24,'24 heures avant'],[48,'48 heures avant']],cfg.cancelHours)}<div class="note"><strong>Réservation automatique</strong><p>Seuls vos créneaux éligibles sont vendus. Aucun aller-retour d’acceptation. En cas d’annulation par le coach, le client est intégralement remboursé dans la démo.</p></div><p class="small muted space">Un temps fixe entre séances simule ici les déplacements. Le calcul d’itinéraire selon les adresses fera partie du vrai service. Les règles d’annulation sont conservées sur chaque réservation.</p>`;
if(id==='documents')body=`<div class="note"><strong>${cfg.verified?'Profil vérifié · simulation':'Vos justificatifs sont à compléter'}</strong><p>Une saisie de diplôme ne vaut pas vérification. La validation serait réalisée séparément avant mise en ligne.</p></div>${['Identité','Diplôme ou certification','Carte professionnelle si applicable','Assurance professionnelle'].map(t=>`<div class="setting-row"><span>${t}</span><span class="badge">${cfg.verified?'Démo validée':'À fournir'}</span></div>`).join('')}<button type="button" class="pill full space" data-action="simulate-verification">Simuler un dossier vérifié</button><p class="small muted space">Aucun véritable document demandé ou conservé. Le périmètre exact des pièces dépendra du pays et de la discipline.</p>`;
if(id==='payout')body=`<div class="note"><strong>${cfg.payoutReady?'Versements activés · compte de test':'Activez les versements pour publier'}</strong><p>Le prestataire de paiement prendrait en charge la vérification professionnelle et les coordonnées bancaires.</p></div><div class="receipt"><div class="row between"><span>Commission par réservation</span><strong>15 %</strong></div><div class="row between"><span>Abonnement</span><strong>0 €</strong></div><div class="row between"><span>Versement</span><strong>Après la séance</strong></div></div><button type="button" class="pill full" data-action="simulate-payout">${cfg.payoutReady?'Voir le compte de test':'Activer un compte de test'}</button><p class="small muted space">Aucune donnée bancaire ni immatriculation réelle à saisir. Le relevé d’activité est accessible dans l’onglet Activité.</p>`;
if(id==='notifications')body=`<p class="muted subhead">Rester au courant, sans multiplier les sollicitations.</p>${[['booking','Nouvelle réservation'],['changes','Modification ou annulation'],['reminder','Rappel avant une séance'],['marketing','Actualités et conseils Partant']].map(([k,t])=>`<label class="setting-row"><span>${t}</span><input class="switch-check" type="checkbox" name="${k}" ${cfg.notifications[k]?'checked':''}></label>`).join('')}<p class="note space">Préférences enregistrées localement. Aucune notification réelle n’est envoyée.</p>`;
if(id==='calendars')body=`<p class="muted subhead">Une source de vérité, même avec plusieurs agendas.</p>${['Google Calendar','Apple Calendar','Outlook'].map(t=>`<div class="setting-row"><span>${t}</span><span class="badge">À connecter en production</span></div>`).join('')}<div class="note space">Un événement occupé masquerait les créneaux publics ; une réservation créerait un événement. Les conflits seraient contrôlés avant paiement.</div><button type="button" class="pill light full space" data-action="private-event">Simuler un événement occupé</button><p class="small muted space">L’ajout simulé a un effet réel sur les disponibilités de la démo. Aucune synchronisation externe n’est revendiquée.</p>`;
return `${pagebar(entry?.[2]||'Configuration')}<div class="section"><p class="eyebrow muted subhead">${state.wizard?'MISE EN LIGNE · PAS À PAS':'VOS RÉGLAGES'}</p><form id="config-form" data-section="${id}">${body}${!['documents','payout','calendars'].includes(id)?'<p id="config-error" role="alert" class="small space"></p><button class="pill full space">Enregistrer'+(state.wizard?' et continuer':'')+'</button>':''}</form></div>`}
function account(){return `<div class="section"><div class="wordmark">partant</div><h1 style="margin:28px 0 18px">Bonjour, ${esc(customer.name)}.</h1><p class="muted">Vos envies évoluent. Partant aussi.</p><div class="preference-ticket space"><p class="eyebrow">VOTRE POINT DE DÉPART</p><h3 style="margin:12px 0">${esc(customer.goal)}</h3><p>${esc(customer.sport==='Tout'?'Toutes les pratiques':customer.sport)} · ${esc(customer.city)}<br>Jusqu’à ${customer.budget} € · ${customer.distance} km</p><button class="textbtn" data-action="preferences">Ajuster mes préférences</button></div><button class="setting-row" data-action="nav" data-id="bookings"><span class="row">${ic('calendar')} Mes séances</span>${ic('chevron')}</button><button class="setting-row" data-action="nav" data-id="favorites"><span class="row">${ic('heart')} Mes coachs favoris</span>${ic('chevron')}</button><button class="setting-row" data-action="customer-settings"><span class="row">${ic('user')} Mon compte & mes rappels</span>${ic('chevron')}</button><button class="setting-row" data-action="trust"><span class="row">${ic('shield')} Confiance & sécurité</span>${ic('chevron')}</button><button class="setting-row" data-action="help"><span class="row">${ic('message')} Aide & annulations</span>${ic('chevron')}</button><div class="note space"><h3>Vous êtes aussi coach ?</h3><p class="muted" style="margin:8px 0 16px">Un espace dédié à votre activité, avec vos propres réglages.</p><button class="pill full" data-action="switch-coach">Passer côté coach</button></div><button class="textbtn full" data-action="logout">${state.auth?'Me déconnecter':'Me connecter'}</button><details class="space"><summary class="small muted" style="min-height:44px;cursor:pointer">À propos de ce prototype</summary><p class="small muted">Démo figée au 14 septembre 2026 à 08:00. Paiements, messages, vérifications et comptes fictifs. Stockage dans ce navigateur uniquement.</p><button class="textbtn full" data-action="complete-demo">Simuler une séance terminée</button><button class="textbtn full" data-action="reset-demo">Réinitialiser la démo</button></details></div>`}
function sessionMarkup(html,b){if(!b)return html;let h=b.cancelHours??(b.coach===0?cfg.cancelHours:24);return html.replaceAll('60 min',(b.duration||60)+' min').replaceAll('24 h',h+' h').replaceAll('24 heures',h+' heures')}
function render(){syncCoach();let pages={welcome,login,code:codeScreen,onboarding,explore:()=>{let html=explore();if(customer.done)html=html.replace('Trouvez votre coach. Réservez votre moment.',`<button class="preference-link" data-action="preferences">Selon vos envies · Ajuster ${ic('filter','sm')}</button>`).replace('Des coachs, tout près.','Pour vous, tout près.');return html},favorites,bookings,account,profile:()=>{let c=coaches[state.coach],s=primaryService(c.id),html=profile().replaceAll('60 min',s.duration+' min').replaceAll('60 minutes',s.duration+' minutes');if(c.id===0)html=html.replaceAll('24 h',cfg.cancelHours+' h').replaceAll('Profil vérifié',cfg.verified?'Profil vérifié':'Vérification en attente');return html},setup,checkout:()=>sessionMarkup(checkout(),state.booking),confirmation:()=>sessionMarkup(confirmation(),findBooking()),detail:()=>sessionMarkup(bookingDetail(),findBooking()),coach:coachHome,config:configPage,'coach-wizard':checklist,client:clientDetail};view.innerHTML=`<div class="screen">${(pages[state.screen]||explore)()}</div>`;nav();let pro=['coach','config','client','coach-wizard'].includes(state.screen);if(pro)document.getElementById('nav').innerHTML=coachNavigation();document.getElementById('nav').classList.toggle('hidden',['welcome','login','code','onboarding','setup','checkout','confirmation','coach-wizard'].includes(state.screen));}
function coachChat(id){state.chatClient=id;let c=clientData().find(c=>c.id===id)||clientData()[0],realMessages=id==='alex'?state.bookings.filter(b=>b.coach===0).flatMap(b=>(state.messages[b.id]||[]).map(t=>({text:t,mine:false}))):[],own=cfg.coachMessages[id]||[];showModal('Conversation · '+c.name,`<p class="small muted">Messagerie locale de démonstration</p><div class="chat">${[...realMessages,...own].map(m=>`<div class="bubble ${m.mine?'mine':''}">${esc(m.text)}</div>`).join('')||'<p class="muted">Le début d’une bonne relation.</p>'}</div><form id="coach-message-form"><label class="field">Votre message<textarea name="text" required maxlength="600" placeholder="Un conseil avant la prochaine séance…"></textarea></label><button class="pill full">Envoyer dans la démo</button></form>`)}
function editService(id){let s=cfg.services.find(s=>s.id===id)||{id:'new',name:'',kind:'Individuel',duration:60,price:50};showModal(id?'Modifier la séance':'Votre nouvelle séance',`<form id="service-form" data-id="${s.id}">${inputField('Nom de la séance','name',s.name,'text','required maxlength="60"')}${selectField('Format','kind',['Individuel','Duo'],s.kind)}${selectField('Durée','duration',[[30,'30 minutes'],[45,'45 minutes'],[60,'60 minutes'],[90,'90 minutes']],s.duration)}${inputField('Prix total de la séance (€)','price',s.price,'number','min="20" max="80" required')}<p class="note">Le prix duo correspond à deux participants au total. Les cours collectifs avec gestion des places appartiennent à une prochaine étape du produit.</p><button class="pill full space">Enregistrer la séance</button></form>`)}
function privateEvent(){showModal('Bloquer un moment',`<form id="private-event-form">${selectField('Jour','day',days.map((d,i)=>[i,d.long]),state.coachDay)}<div class="split">${inputField('De','start','14:00','time','required')}${inputField('À','end','15:00','time','required')}</div>${inputField('Libellé privé','title','Rendez-vous personnel','text','required maxlength="100"')}<p id="event-error" role="alert" class="small"></p><button class="pill full space">Bloquer ce créneau</button><p class="small muted space">Le libellé reste dans l’espace coach. Les clients voient simplement un créneau indisponible.</p></form>`)}
function coachSession(id){state.selectedBooking=id;let b=findBooking();showModal('Votre séance avec '+(b.clientName||'Alex'),`<h3>${dayLabel(b.day)} · ${b.time}</h3><p class="muted">${esc(b.serviceName||b.kind)} · ${b.duration||60} min · ${b.price} €</p><div class="note space"><strong>${locationFor(b).name}</strong><p>${esc(locationFor(b).address)}</p></div><h3 class="space subhead">Objectif de la séance</h3><p>${esc(b.goal||customer.goal)}</p><button class="pill light full space" data-action="client" data-id="alex">Voir la fiche client</button>${b.status==='confirmed'?`<button class="setting-row" data-action="coach-cancel" data-id="${b.id}">Annuler et rembourser intégralement ${ic('chevron')}</button><details class="space"><summary class="small muted" style="min-height:44px">Simuler l’après-séance</summary><button class="textbtn full" data-action="coach-complete" data-id="${b.id}">Marquer comme terminée dans la démo</button><button class="textbtn full" data-action="coach-no-show" data-id="${b.id}">Signaler une absence dans la démo</button></details>`:`<p class="note space">${b.status==='completed'?'Séance terminée':b.status==='no-show'?'Absence enregistrée':'Séance annulée · remboursement '+(b.refund||0)+' €'}</p>`}`)}
function downloadText(filename,text,type){let url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function act(a,d){switch(a){
case 'entry-role':state.entryRole=d.id;render();return;
case 'entry-next':state.entryMode='login';go('login');return;
case 'entry-signup':state.entryMode='signup';go('login');return;
case 'guest':state.auth=null;go('explore');return;
case 'preferences':state.onboardStep=0;go('onboarding');return;
case 'skip-onboard':customer.done=true;applyPreferences();persist();go('explore');return;
case 'switch-coach':state.auth={role:'coach'};state.coachTab='agenda';persist();go('coach');return;
case 'switch-client':state.auth={role:'client'};applyPreferences();persist();go('explore');return;
case 'logout':state.auth=null;persist();state.history=[];go('welcome');return;
case 'nav':if(d.id==='coach'){state.auth={role:'coach'};persist()}break;
case 'scenario':if(d.id==='coach'){state.auth={role:'coach'};state.coachTab='agenda';persist();go('coach');return}break;
case 'coach-tab':state.coachTab=d.id;state.wizard=false;closeModal();go('coach');return;
case 'coach-wizard':state.wizard=true;go('coach-wizard');return;
case 'config':state.configSection=d.id;go('config');return;
case 'coach-day':state.coachDay=+d.id;{let y=view.scrollTop;render();view.scrollTop=y}return;
case 'coach-toggle':{let k=key(0,state.coachDay,d.time);if(state.bookings.some(b=>b.coach===0&&b.day===state.coachDay&&b.status==='confirmed'&&overlaps(mins(d.time),primaryService(0).duration,mins(b.time),b.duration||60,cfg.buffer))){toast('Ce créneau protège une réservation existante.');return}state.closed=state.closed.includes(k)?state.closed.filter(x=>x!==k):[...state.closed,k];persist();let y=view.scrollTop;render();view.scrollTop=y;toast(state.closed.includes(k)?'Créneau fermé':'Créneau rouvert');return}
case 'edit-service':editService(d.id);return;
case 'new-service':editService();return;
case 'toggle-service':{let s=cfg.services.find(s=>s.id===d.id);s.active=!s.active;if(!cfg.services.some(s=>s.active))cfg.published=false;persist();render();return}
case 'select-service':{let b=state.booking,s=servicesFor(b.coach).find(s=>s.id===d.id);if(!s)return;let changed=b.duration!==s.duration;Object.assign(b,{serviceId:s.id,serviceName:s.name,kind:s.kind,duration:s.duration});if(changed)b.time='';render();return}
case 'checkout':{let b=state.booking;if(!b.time)return;if(b.format==='Domicile'){let h=document.getElementById('home-address');if(!h.value.trim()||!document.getElementById('zone-confirm').checked){toast('Renseignez l’adresse et confirmez la zone de déplacement.');h.focus();return}b.home=h.value.trim()}b.goal=document.getElementById('session-goal').value.trim();b.cancelHours=b.coach===0?cfg.cancelHours:24;go('checkout');return}
case 'kind':{let s=servicesFor(state.booking.coach).find(s=>s.kind===d.id);if(s)act('select-service',{id:s.id});return}
case 'client':state.clientId=d.id;closeModal();go('client');return;
case 'coach-chat':coachChat(d.id);return;
case 'private-event':privateEvent();return;
case 'delete-private':cfg.privateEvents=cfg.privateEvents.filter(e=>e.id!==d.id);persist();render();return;
case 'publication':showModal(cfg.published?'Mettre votre profil en pause ?':'Réouvrir votre profil ?',`<p>${cfg.published?'Les nouvelles réservations seront suspendues. Vos séances déjà confirmées restent dans votre agenda.':'Votre offre sera de nouveau réservable selon votre planning et vos règles.'}</p><button class="pill full space" data-action="confirm-publication">${cfg.published?'Mettre en pause':'Réouvrir les réservations'}</button><button class="textbtn full" data-action="close">Revenir aux réglages</button>`);return;
case 'confirm-publication':if(!cfg.published&&!publicationReady()){closeModal();go('coach-wizard');toast('Terminez la configuration avant de publier.');return}cfg.published=!cfg.published;persist();closeModal();render();return;
case 'publish':if(!publicationReady())return;cfg.published=true;persist();state.wizard=false;state.coach=0;go('profile');return;
case 'simulate-verification':cfg.verified=true;persist();toast('Dossier de test vérifié. Aucun document réel contrôlé.');go(state.wizard?'coach-wizard':'config');return;
case 'simulate-payout':cfg.payoutReady=true;persist();if(state.wizard){go('coach-wizard');return}showModal('Compte de versement de test','<div class="note"><strong>Thomas Martin · compte fictif</strong><p>Identité professionnelle : simulation validée.<br>Versements : après la séance.<br>Commission : 15 %.</p></div><p class="small muted space">Aucun compte bancaire connecté. Aucun virement réel.</p>');return;
case 'coach-session':coachSession(d.id);return;
case 'coach-cancel':state.selectedBooking=d.id;showModal('Annuler côté coach',`<p>Le client sera intégralement remboursé : <strong>${findBooking().price} €</strong>.</p><form id="coach-cancel-form" class="space">${selectField('Motif visible du client','reason',['Indisponibilité exceptionnelle','Lieu indisponible','Conditions météo','Autre imprévu'],'Indisponibilité exceptionnelle')}<button class="pill full">Confirmer l’annulation et le remboursement simulé</button></form>`);return;
case 'coach-complete':{let b=state.bookings.find(b=>b.id===d.id);b.status='completed';persist();closeModal();render();toast('Séance terminée dans la démo');return}
case 'coach-no-show':showModal('Confirmer l’absence ?',`<p>L’absence sera enregistrée sur cette séance de démonstration. Le prix reste dû ; aucune pénalité supplémentaire.</p><button class="pill full space" data-action="confirm-no-show" data-id="${d.id}">Confirmer l’absence dans la démo</button>`);return;
case 'confirm-no-show':{let b=state.bookings.find(b=>b.id===d.id);b.status='no-show';persist();closeModal();render();return}
case 'export-sales':{let rows=[['Référence','Date','Heure','Client','Offre','Statut','Montant EUR','Remboursement EUR','Commission EUR','Net EUR'],...state.bookings.filter(b=>b.coach===0).map(b=>{let net=b.price-(b.refund||0);return [b.id,dayLabel(b.day),b.time,b.clientName||'Alex',b.serviceName||b.kind,b.status,b.price,b.refund||0,(net*.15).toFixed(2),(net*.85).toFixed(2)]})];let csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'").replaceAll('"','""')+'"').join(';')).join('\r\n');downloadText('partant-releve-demo.csv',csv,'text/csv;charset=utf-8');toast('Relevé de démonstration téléchargé');return}
case 'customer-settings':showModal('Mon compte & mes rappels',`<form id="customer-settings-form">${inputField('Votre prénom','name',customer.name,'text','required maxlength="40"')}<label class="setting-row"><span>Me rappeler mes séances</span><input class="switch-check" type="checkbox" name="reminders" ${customer.reminders?'checked':''}></label><p class="small muted space">Préférence enregistrée localement, sans envoi réel.</p><button class="pill full space">Enregistrer</button></form>`);return;
case 'confirm-reschedule':{let b=findBooking(),r=state.rescheduleChoice;if(!avail(coaches[b.coach],r.day,b.id).includes(r.time)||state.bookings.some(x=>x.id!==b.id&&x.status==='confirmed'&&x.day===r.day&&overlaps(mins(x.time),x.duration||60,mins(r.time),b.duration||60))){toast('Ce créneau est indisponible ou chevauche une séance.');dateModal('reschedule',r.day);return}Object.assign(b,r);persist();state.dateMode='';closeModal();render();toast('Séance déplacée. Pensez à actualiser votre calendrier.');return}
case 'close':state.dateMode='';break;
case 'confirm-reset':{try{localStorage.removeItem('partant-v2')}catch(e){}legacyAct(a,d);state.auth=null;customer.done=false;state.screen='welcome';render();return}
}
legacyAct(a,d);
}
function configSave(form){let f=new FormData(form),id=form.dataset.section,error=document.getElementById('config-error'),v=k=>f.get(k),n=k=>Number(v(k));let problem='';if(id==='profile'){if(!v('name').trim()||!v('bio').trim()||!v('cert').trim())problem='Complétez le nom, la présentation et les qualifications.';else{let changed=cfg.cert!==v('cert')||cfg.name!==v('name');Object.assign(cfg,{name:v('name').trim(),sport:v('sport'),bio:v('bio').trim(),cert:v('cert').trim(),langs:v('langs').trim(),experience:n('experience')});if(changed){cfg.verified=false;cfg.published=false}cfg.checks.profile=true}}
if(id==='offers')cfg.checks.offers=cfg.services.some(s=>s.active);
if(id==='places'){let formats=f.getAll('formats');if(!formats.length)problem='Choisissez au moins un format de séance.';else if(formats.includes('Studio')&&(!v('studio').trim()||!v('studioAddress').trim()))problem='Précisez le nom et l’adresse du studio.';else{Object.assign(cfg,{formats,place:v('place').trim(),address:v('address').trim(),studio:v('studio').trim(),studioAddress:v('studioAddress').trim(),radius:n('radius'),travelFee:n('travelFee')});cfg.checks.places=true}}
if(id==='schedule'){if(mins(v('start'))>=mins(v('end')))problem='La fin de journée doit être après le début.';else if(f.has('useBreak')&&(mins(v('breakStart'))>=mins(v('breakEnd'))||mins(v('breakStart'))<mins(v('start'))||mins(v('breakEnd'))>mins(v('end'))))problem='La pause doit se situer à l’intérieur de la journée, avec une fin après son début.';else if(!f.getAll('week').length)problem='Ouvrez au moins un jour dans votre semaine type.';else{Object.assign(cfg,{weeklyConfigured:true,week:Array.from({length:7},(_,i)=>f.getAll('week').includes(String(i))),start:v('start'),end:v('end'),useBreak:f.has('useBreak'),breakStart:v('breakStart'),breakEnd:v('breakEnd'),daysOff:f.getAll('daysOff').map(Number)});cfg.checks.schedule=true}}
if(id==='rules')Object.assign(cfg,{buffer:n('buffer'),notice:n('notice'),horizon:n('horizon'),cancelHours:n('cancelHours')});
if(id==='notifications')for(let k of Object.keys(cfg.notifications))cfg.notifications[k]=f.has(k);
if(problem){error.textContent=problem;error.scrollIntoView({block:'nearest'});return}syncCoach();persist();if(state.wizard)go('coach-wizard');else render();toast('Réglages enregistrés. Les réservations déjà payées sont conservées.');}
document.addEventListener('submit',e=>{let form=e.target,id=form.id;if(!['entry-form','code-form','onboard-form','config-form','service-form','private-event-form','client-note-form','coach-message-form','coach-cancel-form','customer-settings-form'].includes(id))return;e.preventDefault();let f=new FormData(form);
if(id==='entry-form'){if(f.get('name'))customer.name=f.get('name').trim();go('code')}
if(id==='code-form'){if(f.get('code')!=='123456'){document.getElementById('code-error').textContent='Utilisez le code de démonstration 123456.';return}state.auth={role:state.entryRole};if(state.entryRole==='coach'){state.coachTab='agenda';if(state.entryMode==='signup'){cfg.published=false;cfg.verified=false;cfg.payoutReady=false;cfg.checks={profile:false,offers:false,places:false,schedule:false};state.wizard=true;persist();go('coach-wizard')}else{persist();go('coach')}}else{persist();if(!customer.done){state.onboardStep=0;go('onboarding')}else{applyPreferences();go('explore')}}}
if(id==='onboard-form'){for(let [k,v]of f.entries())customer[k]=['budget','distance'].includes(k)?+v:v;persist();if(state.onboardStep<2){state.onboardStep++;render();view.scrollTop=0}else{customer.done=true;applyPreferences();persist();go('explore')}}
if(id==='config-form')configSave(form);
if(id==='service-form'){let service={id:form.dataset.id==='new'?'s-'+Date.now().toString(36):form.dataset.id,name:f.get('name').trim(),kind:f.get('kind'),duration:+f.get('duration'),price:+f.get('price'),active:true};if(!service.name||service.price<20||service.price>80)return;let i=cfg.services.findIndex(s=>s.id===service.id);if(i<0)cfg.services.push(service);else cfg.services[i]={...cfg.services[i],...service};cfg.checks.offers=true;persist();closeModal();render();toast('Offre enregistrée')}
if(id==='private-event-form'){let d=+f.get('day'),start=f.get('start'),end=f.get('end'),err=document.getElementById('event-error');if(mins(end)<=mins(start)){err.textContent='La fin doit être après le début.';return}if(state.bookings.some(b=>b.coach===0&&b.status==='confirmed'&&b.day===d&&overlaps(mins(start),mins(end)-mins(start),mins(b.time),b.duration||60))){err.textContent='Une séance est déjà réservée sur cette plage. Traitez ce rendez-vous avant de bloquer ce moment.';return}cfg.privateEvents.push({id:'e-'+Date.now(),day:d,start,end,title:f.get('title').trim()});persist();closeModal();render();toast('Indisponibilité ajoutée au planning public')}
if(id==='client-note-form'){cfg.clientNotes[state.clientId]=f.get('note').trim();persist();toast('Notes privées enregistrées')}
if(id==='coach-message-form'){let text=f.get('text').trim();if(!text)return;(cfg.coachMessages[state.chatClient]??=[]).push({text,mine:true});if(state.chatClient==='alex'){let b=state.bookings.filter(b=>b.coach===0&&b.status==='confirmed').at(-1);if(b)(state.messages[b.id]??=[]).push('[Coach] '+text)}persist();coachChat(state.chatClient)}
if(id==='coach-cancel-form'){let b=findBooking();b.status='cancelled';b.refund=b.price;b.cancelledBy='coach';b.cancelReason=f.get('reason');persist();closeModal();render();toast('Séance annulée et remboursement intégral simulé')}
if(id==='customer-settings-form'){customer.name=f.get('name').trim();customer.reminders=f.has('reminders');persist();closeModal();render()}
});
render();
